---
title: "inferCNV"
output: html_document
date: "2024-02-28"
---

```{r}
# Had to use devtools to install
library(infercnv)
```
# Our data
```{r}
library(ArchR)
addArchRThreads(threads = 1)
options(future.globals.maxSize=100000000000000000000000) 

archR <- loadArchRProject(path = "/Users/gagled01/morganLab/Waldenstroms/singlecell/data/ATAC_fragments/WM_DeviationsAdded")
archR$annotation2 <- archR$annotation1
archR$annotation2[archR$annotation1 == "C3 - Non-clonal PC"] <- "C1 - Clonal PCs"
archR$annotation2[archR$annotation1 == "C5 - WM54 Secondary Clone"] <- "C2 - Clonal MBC"
archR$annotation2[archR$annotation1 == "C6 - Clonal MBC Minor Cluster 1"] <- "C2 - Clonal MBC"
archR$annotation2[archR$annotation1 == "C7 - Clonal MBC Minor Cluster 2"] <- "C2 - Clonal MBC"

archR$tripartite_annotation <- archR$annotation3
archR$tripartite_annotation[archR$samplesClean == "WM43"] <- "Intermediate MBC"
archR$tripartite_annotation[archR$annotation1 == "C5 - WM54 Secondary Clone"] <- "MBC-like MBC"
archR$tripartite_annotation[archR$annotation3 == "MBC-like MBC" & archR$samplesClean == "04-006"] <- "PC-like MBC"
archR$tripartite_annotation[archR$annotation3 == "MBC-like MBC" & archR$samplesClean == "01-115"] <- "PC-like MBC"
archR$tripartite_annotation[archR$annotation3 == "PC-like MBC" & archR$samplesClean == "01-190"] <- "MBC-like MBC"
archR$tripartite_annotation[archR$annotation3 == "PC-like MBC" & archR$samplesClean == "WM25"] <- "Intermediate MBC"
archR$tripartite_annotation[archR$annotation1 == "C2 - Clonal MBC" & archR$samplesClean == "WM54"] <- "Intermediate MBC"


archR$annotation2 <- archR$annotation1
archR$annotation2[archR$annotation1 == "C3 - Non-clonal PC"] <- "C1 - Clonal PCs"
archR$annotation2[archR$annotation1 == "C5 - WM54 Secondary Clone"] <- "C2 - Clonal MBC"
archR$annotation2[archR$annotation1 == "C6 - Clonal MBC Minor Cluster 1"] <- "C2 - Clonal MBC"
archR$annotation2[archR$annotation1 == "C7 - Clonal MBC Minor Cluster 2"] <- "C2 - Clonal MBC"
archR$annotation2[archR$annotation2 == "C1 - Clonal PCs"] <- "Clonal PCs"
archR$annotation2[archR$annotation1 == "C10 - HD Memory B cells"] <- "Reference MBC"
archR$annotation2[archR$annotation1 == "C11 - HD Plasma cells"] <- "Reference PC"
archR$annotation2[archR$annotation2 == "C2 - Clonal MBC"] <- "Clonal MBC"
archR$annotation2[archR$annotation1 == "C4 - Non-clonal MBC"] <- "Non-clonal MBC"
archR$annotation2[archR$annotation1 == "C8 - HD GC B cells"] <- "Reference GC"
archR$annotation2[archR$annotation1 == "C9 - HD Naive B cells"] <- "Reference Naive"
table(archR$annotation2)

archR$annotation3 <- archR$annotation2
archR$annotation3[archR$annotation2 == "Clonal MBC" & archR$hasPC == "+"] <- "PC-like MBC"
archR$annotation3[archR$annotation2 == "Clonal MBC" & archR$hasPC == "-"] <- "MBC-like MBC"
archR$annotation3[archR$annotation3 == "Clonal MBC"] <- "PC-like MBC"
table(archR$annotation3)

archR$annotation4 <- archR$annotation2
archR$annotation4[archR$hasPC == "+"] <- "PC-like"
archR$annotation4[archR$hasPC == "-"] <- "MBC-like"
archR$annotation4[archR$condition == "HD"] <- "Reference"

archR$subtype <- archR$hasPC 
archR$subtype[archR$hasPC == "+"] <- "PC-like"
archR$subtype[archR$hasPC == "-"] <- "MBC-like"
table(archR$subtype)

archR$annotation5 <- archR$annotation1
archR$annotation5[archR$annotation1 == "C3 - Non-clonal PC"] <- "Clonal PC"
archR$annotation5[archR$annotation1 == "C5 - WM54 Secondary Clone"] <- "Clonal MBC"
archR$annotation5[archR$annotation1 == "C6 - Clonal MBC Minor Cluster 1"] <- "Clonal MBC"
archR$annotation5[archR$annotation1 == "C7 - Clonal MBC Minor Cluster 2"] <- "Clonal MBC"
archR$annotation5[archR$annotation5 == "C1 - Clonal PCs"] <- "Clonal PC"
archR$annotation5[archR$annotation1 == "C10 - HD Memory B cells"] <- "Reference MBC"
archR$annotation5[archR$annotation1 == "C11 - HD Plasma cells"] <- "Reference PC"
archR$annotation5[archR$annotation5 == "C2 - Clonal MBC"] <- "Clonal MBC"
archR$annotation5[archR$annotation1 == "C4 - Non-clonal MBC"] <- "Non-clonal MBC"
archR$annotation5[archR$annotation1 == "C8 - HD GC B cells"] <- "Reference GC"
archR$annotation5[archR$annotation1 == "C9 - HD Naive B cells"] <- "Reference Naive"
table(archR$annotation5)

archR$inferCNV_annotation <- archR$annotation5
#archR$inferCNV_annotation[archR$condition == "HD"] <- "Reference"
table(archR$inferCNV_annotation)
```
# Patient subset function
```{r}
patient_subset <- function(archR_obj, id_str) {
  idx <- BiocGenerics::which(archR$samplesClean == id_str)
  cells <- archR_obj$cellNames[idx]
  sub_archR <- archR_obj[cells,]
  return(sub_archR)
}

advanced_subset <- function(archR_obj, id_str) {
  cellsKeep <- archR_obj$cellNames[archR_obj$samplesClean %in% c(id_str)]
  cellsKeep2 <- archR_obj$cellNames[archR_obj$inferCNV_annotation %in% c("Reference MBC", "Reference PC")]
  cellsKeep3 <- c(cellsKeep, cellsKeep2)
  sub_archR <- archR_obj[cellsKeep3,]
  return(sub_archR)
}

extract_matrix <- function(archr) {
  se.matrix <- getMatrixFromProject(
    ArchRProj = archr,
    useMatrix = "GeneIntegrationMatrix",
    useSeqnames = NULL,
    verbose = TRUE,
    binarize = FALSE,
    threads = getArchRThreads(),
  )
  raw_matrix <- assays(se.matrix)$GeneIntegrationMatrix
  cols <- colnames(raw_matrix)
  cols2 <- gsub("fragments.tsv.gz#", "", cols)
  cols3 <- gsub("fragments.tsv.bgz#", "", cols2)
  rows <- rowData(se.matrix)$name
  dimnames(raw_matrix) = list(rows,cols3)
  df.matrix <- as.data.frame(raw_matrix)
  return(df.matrix)
}
```

```{r}
# Advanced
#p01_076_advanced <- advanced_subset(archR, "01-076")
#p01_115_advanced <- advanced_subset(archR, "01-115")
#p01_131_advanced <- advanced_subset(archR, "01-131")
#p01_163_advanced <- advanced_subset(archR, "01-163")
#p01_190_advanced <- advanced_subset(archR, "01-190")
#p04_003_advanced <- advanced_subset(archR, "04-003")
#p04_006_advanced <- advanced_subset(archR, "04-006")
#wm25_advanced <- advanced_subset(archR, "WM25")
wm43_advanced <- advanced_subset(archR, "WM43")
#wm46_advanced <- advanced_subset(archR, "WM46")
#wm47_advanced <- advanced_subset(archR, "WM47")
wm65_advanced <- advanced_subset(archR, "WM65")
#wm54_advanced <- advanced_subset(archR, "WM54")

p01_076_raw.matrix <- extract_matrix(p01_076_advanced)
#p01_115_raw.matrix <- extract_matrix(p01_115_advanced)
#p01_131_raw.matrix <- extract_matrix(p01_131_advanced)
#p01_163_raw.matrix <- extract_matrix(p01_163_advanced)
#p01_190_raw.matrix <- extract_matrix(p01_190_advanced)
#p04_003_raw.matrix <- extract_matrix(p04_003_advanced)
#p04_006_raw.matrix <- extract_matrix(p04_006_advanced)
#wm25_raw.matrix <- extract_matrix(wm25_advanced)
wm43_raw.matrix <- extract_matrix(wm43_advanced)
#wm46_raw.matrix <- extract_matrix(wm46_advanced)
#wm47_raw.matrix <- extract_matrix(wm47_advanced)
#wm54_raw.matrix <- extract_matrix(wm54_advanced)
wm65_raw.matrix <- extract_matrix(wm65_advanced)
```
# Make annotation file
```{r}
make_anno <- function(archr) {
  cells <- archr$cellNames
  cells2 <- gsub(".*#", "", cells) # fix cells
  category <- archr$annotation5 
  
  patient_str <- archr$samplesClean[1]
  
  annotation.file <- as.data.frame(matrix(ncol = 2, nrow = length(cells)))
  annotation.file$V1 <- cells2
  annotation.file$V2 <- category
  names(annotation.file) <- NULL
  
  write.table(annotation.file, file=paste0("/Users/gagled01/morganLab/Waldenstroms/singlecell/inferCNV/annotations/", patient_str, "_annotation.file.tsv", collapse = ""), quote=FALSE, sep="\t", row.names = FALSE)
}

###################

make_anno_advanced <- function(archr) {
  cells <- archr$cellNames
  cells2 <- gsub("fragments.tsv.gz#", "", cells) # fix cells
  cells3 <- gsub("fragments.tsv.bgz#", "", cells2) # more fix
  category <- archr$inferCNV_annotation 
  
  patient_str <- archr$samplesClean[1]
  
  annotation.file <- as.data.frame(matrix(ncol = 2, nrow = length(cells)))
  annotation.file$V1 <- cells3
  annotation.file$V2 <- category
  names(annotation.file) <- NULL
  
  write.table(annotation.file, file=paste0("/Users/gagled01/morganLab/Waldenstroms/singlecell/inferCNV/annotations/", patient_str, "_advanced_annotation.file.tsv", collapse = ""), quote=FALSE, sep="\t", row.names = FALSE)
}

make_anno_hpc_compat <- function(archr) {
  cells <- archr$cellNames
  cells2 <- gsub("fragments.tsv.gz#", "", cells) # fix cells
  cells3 <- gsub("fragments.tsv.bgz#", "", cells2) # more fix
  cells4 <- gsub("-1", ".1", cells3)
  category <- archr$inferCNV_annotation 
  
  patient_str <- archr$samplesClean[1]
  
  annotation.file <- as.data.frame(matrix(ncol = 2, nrow = length(cells)))
  annotation.file$V1 <- cells4
  annotation.file$V2 <- category
  names(annotation.file) <- NULL
  
  write.table(annotation.file, file=paste0("/Users/gagled01/morganLab/Waldenstroms/singlecell/inferCNV/annotations/", patient_str, "_advanced_annotation.file.tsv", collapse = ""), quote=FALSE, sep="\t", row.names = FALSE)
}
```

```{r}
## Advanced
make_anno_advanced(p01_076_advanced)
make_anno_advanced(p01_115_advanced)
make_anno_advanced(p01_131_advanced)
make_anno_advanced(p01_163_advanced)
make_anno_advanced(p01_190_advanced)
make_anno_advanced(p04_003_advanced)
make_anno_advanced(p04_006_advanced)
make_anno_advanced(wm25_advanced)
make_anno_advanced(wm43_advanced)
make_anno_advanced(wm46_advanced)
make_anno_advanced(wm47_advanced)
make_anno_advanced(wm54_advanced)
make_anno_advanced(wm65_advanced)
```
Create object and run inferCNV
```{r}
advanced_infercnv_obj = CreateInfercnvObject(raw_counts_matrix=wm65_raw.matrix,
                                   annotations_file="/Users/gagled01/morganLab/Waldenstroms/singlecell/inferCNV/annotations/WM65_advanced_annotation.file.tsv",
                                    delim="\t",
                                    gene_order_file="/Users/gagled01/morganLab/Waldenstroms/singlecell/inferCNV/hg38_gencode_v27.txt",
                                    ref_group_names=c("Reference MBC", "Reference PC")) 

advanced_infercnv_obj = infercnv::run(advanced_infercnv_obj,
                             cutoff=0.1, # cutoff=1 works well for Smart-seq2, and cutoff=0.1 works well for 10x Genomics
                             out_dir="/Users/gagled01/morganLab/Waldenstroms/singlecell/inferCNV/output/WM65", 
                             cluster_by_groups=TRUE, 
                             denoise=TRUE,
                             sd_amplifier = 2,
                             HMM=TRUE)
```

