---
title: "Malignant_Comparison_GEX"
output: html_document
date: "2024-01-25"
---

```{r}
library(ArchR)
library(Seurat)
addArchRThreads(threads = 1)
#addArchRGenome("hg38")
options(future.globals.maxSize=100000000000000000000000) 
```
Load existing ArchR project
```{r}
archR <- loadArchRProject(path = "/Users/gagled01/morganLab/Waldenstroms/singlecell/data/ATAC_fragments/WM_2024_PeaksAdded")
```
# Fix CXCR4 status
```{r}
archR_coreMalignants$cxcr4 <- archR_coreMalignants$samplesClean
cxcr4.1 <- gsub("01-190", "+", archR_coreMalignants$cxcr4)
archR_coreMalignants$cxcr4 <- cxcr4.1
cxcr4.2 <- gsub("04-006", "+", archR_coreMalignants$cxcr4)
archR_coreMalignants$cxcr4 <- cxcr4.2
cxcr4.3 <- gsub("01-...", "-", archR_coreMalignants$cxcr4)
archR_coreMalignants$cxcr4 <- cxcr4.3
cxcr4.4 <- gsub("04-...", "-", archR_coreMalignants$cxcr4)
archR_coreMalignants$cxcr4 <- cxcr4.4
cxcr4.5 <- gsub("WM25", "-", archR_coreMalignants$cxcr4)
archR_coreMalignants$cxcr4 <- cxcr4.5
cxcr4.6 <- gsub("WM43", "+", archR_coreMalignants$cxcr4)
archR_coreMalignants$cxcr4 <- cxcr4.6
cxcr4.7 <- gsub("WM46", "-", archR_coreMalignants$cxcr4)
archR_coreMalignants$cxcr4 <- cxcr4.7
cxcr4.8 <- gsub("WM47", "-", archR_coreMalignants$cxcr4)
archR_coreMalignants$cxcr4 <- cxcr4.8
cxcr4.9 <- gsub("WM54", "-", archR_coreMalignants$cxcr4)
archR_coreMalignants$cxcr4 <- cxcr4.9
cxcr4.10 <- gsub("WM65", "+", archR_coreMalignants$cxcr4)
archR_coreMalignants$cxcr4 <- cxcr4.10
cxcr4.11 <- gsub("BCP00.", "NA", archR_coreMalignants$cxcr4)
archR_coreMalignants$cxcr4 <- cxcr4.11
cxcr4.12 <- gsub("stanford_.", "NA", archR_coreMalignants$cxcr4)
archR_coreMalignants$cxcr4 <- cxcr4.12
table(archR_coreMalignants$cxcr4)
```

# Comparing malignants
```{r}
# Remove WM43 which has fucked up PC profile which is messing things up
cellsKeep <- archR$cellNames[archR$condition == "WM" & archR$annotation1 %in% c("C1 - Clonal PCs", "C2 - Clonal MBC")]
archR_coreMalignants <- archR[cellsKeep, ]

#Take PCs and recluster

archR_coreMalignants <- addIterativeLSI(
  ArchRProj = archR_coreMalignants,
  useMatrix = "TileMatrix",
  name = "IterativeLSI_CoreMalignants",
  iterations = 2,
  clusterParams = list( # based on Seurat's FindClusters()
    resolution = c(0.25),
    sampleCells = 2000,
    n.start = 10
  ),
  varFeatures = 20000,
  dimsToUse = 1:20,
  force = T
)

archR_coreMalignants <- addClusters(
  input = archR_coreMalignants,
  reducedDims = "IterativeLSI_CoreMalignants",
  method = "Seurat",
  name = "CoreMalignant_Clusters",
  resolution = 0.5,
  force = T
)

archR_coreMalignants <- addUMAP(
    ArchRProj = archR_coreMalignants, 
    reducedDims = "IterativeLSI_CoreMalignants", 
    name = "CoreMalignant_UMAP", 
    nNeighbors = 30, 
    minDist = 0.5, 
    metric = "cosine",
    force = T
)

plotEmbedding(ArchRProj = archR_coreMalignants, colorBy = "cellColData", name = "samplesClean", embedding = "CoreMalignant_UMAP")
plotEmbedding(ArchRProj = archR_coreMalignants, colorBy = "cellColData", name = "CoreMalignant_Clusters", embedding = "CoreMalignant_UMAP")
plotEmbedding(ArchRProj = archR_coreMalignants, colorBy = "cellColData", name = "condition", embedding = "CoreMalignant_UMAP")
plotEmbedding(ArchRProj = archR_coreMalignants, colorBy = "cellColData", name = "annotation1", embedding = "CoreMalignant_UMAP")
plotEmbedding(ArchRProj = archR_coreMalignants, colorBy = "cellColData", name = "cxcr4", embedding = "CoreMalignant_UMAP")
plotEmbedding(ArchRProj = archR_coreMalignants, colorBy = "cellColData", name = "hasPC", embedding = "CoreMalignant_UMAP")
```
Patient specific marker genes
```{r}
markerTest <- getMarkerFeatures(
  ArchRProj = archR_coreMalignants, 
  useMatrix = "GeneIntegrationMatrix",
  groupBy = "samplesClean",
  testMethod = "wilcoxon",
  bias = c("TSSEnrichment", "log10(nFrags)")
)

markersGEX_list <- getMarkers(markerTest, cutOff = "FDR < 0.1 & Log2FC > 0.5")

# DEG df
deg.df.gex <- markersGEX_list$`WM65`
deg.df.gex <- as.data.frame(deg.df.gex)
head(deg.df.gex[order(-deg.df.gex$MeanDiff),], n = 100)
#head(deg.df.gex[order(-deg.df.gex$MeanDiff),], n = 25)

geneList <- c("ARHGAP24", "SOX5", "UTRN", "MARCH1", "FCHSD2", "CD83", "CD74")
squee <- c("TRAF6", "MAP3K7", "STAT5A", "PIK3CA", "HCK", "BTK", "IBTK", "CD37")
plotEmbedding(archR_coreMalignants, colorBy = "GeneIntegrationMatrix", name = geneList, embedding = "CoreMalignant_UMAP", imputeWeights = getImputeWeights(archR_coreMalignants))
```

```{r}
markerTest <- getMarkerFeatures(
  ArchRProj = archR_coreMalignants, 
  useMatrix = "GeneIntegrationMatrix",
  groupBy = "cxcr4",
  testMethod = "wilcoxon",
  bias = c("TSSEnrichment", "log10(nFrags)")
)

markersGEX_list <- getMarkers(markerTest, cutOff = "FDR < 0.1 & Log2FC > 0.5")

# DEG df
deg.df.gex <- markersGEX_list$`+`
deg.df.gex <- as.data.frame(deg.df.gex)
head(deg.df.gex[order(-deg.df.gex$MeanDiff),], n = 100)
#head(deg.df.gex[order(deg.df.gex$MeanDiff),], n = 50)

geneList <- c("SIPA1L1", "PDE4B", "OSBPL3", "RNF19A", "CYTIP", "CADM2", "CEMIP2", "FAM214A", "CD83", "RASSF6", "FUT8", "NR3C2", "BIRC6",
              "CD69", "GAB1", "MTSS1", "TP53INP1", "FAM107B", "GNAQ", "ASTN2", "AFF1", "YBX3", "CASK", "BICD1", "SSH2", "TPD52", "FGD4",
              "DAAM1", "CHST11", "BBX", "SH3RF1", "GPHN", "MAP4K4", "ARID5B", "ANKRD28")

plotEmbedding(archR_coreMalignants, colorBy = "GeneIntegrationMatrix", name = geneList, embedding = "CoreMalignant_UMAP", imputeWeights = getImputeWeights(archR_coreMalignants))
```




