---
title: "ArchR_MalignantNormal_Comparisons"
output: html_document
date: "2024-01-22"
---

```{r}
library(ArchR)
library(Seurat)
addArchRThreads(threads = 1)
#addArchRGenome("hg38")
options(future.globals.maxSize=100000000000000000000000) 
```
Load existing ArchR project
```{r}
archR <- loadArchRProject(path = "/Users/gagled01/morganLab/Waldenstroms/Waldenstroms_Git/WM_2024_BaselineData")
```
# Check marker genes from King et al 2021 reference data
```{r}
geneList1 <- c("TXNIP", "FCER2", "FCMR", "SELL", "BANK1", "EGR1", "CD69", "DUSP2", "JUN", "IL6", "CCND2", "MIR155HG", "PSME2", "BHLHE40", "PARVB")
geneList2 <- c("JCHAIN", "PRDM1", "XBP1", "MZB1")
geneList3 <- c("EBI3", "BCL2A1", "LMO2", "GMDS", "PRPSAP2", "SERPINA9", "MARCKSL1", "CD27", "CD38", "BCL6", "SUGCT", "EZR", "ISG20", "AICDA", "FCRL3", "FCRL2", "SAMSN1", "SIGLEC10", "RASSF6", "FRZB", "HOPX", "BTNL9", "FGFR1")
geneList4 <- c("HMGB2", "TUBA1B", "MKI67", "UBE2C", "AURKB")
plotEmbedding(archR, colorBy = "GeneIntegrationMatrix", name = geneList1, embedding = "BLineage_NoProgen_Recluster_UMAP", imputeWeights = getImputeWeights(archR))
```
# Comparing malignants and normals ----- PLASMA CELLS ---
```{r}
# Remove WM43 which has fucked up PC profile which is messing things up
cellsKeep <- archR$cellNames[archR$predictedGroup_Un == "Plasma cells"]
archR_pcs_wm43_removed <- archR[cellsKeep, ]

#Take PCs and recluster

archR_pcs_wm43_removed <- addIterativeLSI(
  ArchRProj = archR_pcs_wm43_removed,
  useMatrix = "TileMatrix",
  name = "IterativeLSI_PCs",
  iterations = 2,
  clusterParams = list( # based on Seurat's FindClusters()
    resolution = c(0.25),
    sampleCells = 2000,
    n.start = 10
  ),
  varFeatures = 20000,
  dimsToUse = 1:20,
  force = T
)

archR_pcs_wm43_removed <- addClusters(
  input = archR_pcs_wm43_removed,
  reducedDims = "IterativeLSI_PCs",
  method = "Seurat",
  name = "PCs_Clusters",
  resolution = 0.2,
  force = T
)

archR_pcs_wm43_removed <- addUMAP(
    ArchRProj = archR_pcs_wm43_removed, 
    reducedDims = "IterativeLSI_PCs", 
    name = "PCs_UMAP", 
    nNeighbors = 30, 
    minDist = 0.5, 
    metric = "cosine",
    force = T
)

plotEmbedding(ArchRProj = archR_pcs_wm43_removed, colorBy = "cellColData", name = "samplesClean", embedding = "PCs_UMAP")
plotEmbedding(ArchRProj = archR_pcs_wm43_removed, colorBy = "cellColData", name = "PCs_Clusters", embedding = "PCs_UMAP")
plotEmbedding(ArchRProj = archR_pcs_wm43_removed, colorBy = "cellColData", name = "condition", embedding = "PCs_UMAP")
plotEmbedding(ArchRProj = archR_pcs_wm43_removed, colorBy = "cellColData", name = "annotation1", embedding = "PCs_UMAP") #+ #+ 
```

```{r}
markerTest <- getMarkerFeatures(
  ArchRProj = archR, 
  useMatrix = "GeneIntegrationMatrix",
  groupBy = "annotation1",
  testMethod = "wilcoxon",
  bias = c("TSSEnrichment", "log10(nFrags)"),
  useGroups = c("C2 - Clonal MBC"),
  bgdGroups = c("C4 - Non-clonal MBC", "C10 - HD Memory B cells", "C9 - HD Naive B cells", "C8 - HD GC B cells")
)

markersGEX_list <- getMarkers(markerTest, cutOff = "FDR < 0.1")

# DEG df
deg.df.gex <- markersGEX_list$`C2 - Clonal MBC`
deg.df.gex <- as.data.frame(deg.df.gex)
head(deg.df.gex[order(-deg.df.gex$MeanDiff),], n = 100)
#head(deg.df.gex[order(deg.df.gex$MeanDiff),], n = 50)

geneList <- c("PLCG2", "MALAT1", "ZNF804A", "PELI1", "CDK14", "FOXP1", "BANK1", "HDAC9", "BCL2", "VOPP1", "PRDM2", "TRIO", "AFF3", "TCF4", "SOX5",
              "ZBTB20", "SMCHD1", "ITPR2", "LYN", "MSI2", "PTPRG")
geneList <- c("CD74", "HLA-DRA", "TMSB4X", "EEF1A1", "MS4A1", "ACTB", "TPT1", "PTPRC", "B2M", "ACTG1", "TMSB10", "POU2F2", "CD53", "CD37", "CD22", "BCL11A")
geneList <- c("ARHGAP24", "ZNF804A", "MTRNR2L8", "ARHGAP15", "RALGPS2", "OSBPL10", "AKAP13", "FBXW7", "ITPR2", "CDC42SE2", "HLA-C")
geneList <- c("CD79A", "SYK", "BLNK", "PLCG2", "CARD11", "IL21R", "JAK3", "IFNG", "FOXP1", "CBLB", "MSH6", "IMPDH2", "CCR7", "MEF2C", "ITPKB", "BANK1", "IL7R", "LAX1", "ERCC1", "PRKCB","ITGAL", "GON4L", "PSEN1", "RHOH")
plotEmbedding(archR, colorBy = "GeneIntegrationMatrix", name = geneList, embedding = "BLineage_NoProgen_Recluster_UMAP", imputeWeights = getImputeWeights(archR))

```
Malignant Only patient comparison
```{r}
markerTest <- getMarkerFeatures(
  ArchRProj = archR, 
  useMatrix = "GeneIntegrationMatrix",
  groupBy = "annotation1",
  testMethod = "wilcoxon",
  bias = c("TSSEnrichment", "log10(nFrags)"),
  useGroups = c("C2 - Clonal MBC"),
  bgdGroups = c("C4 - Non-clonal MBC", "C10 - HD Memory B cells", "C9 - HD Naive B cells", "C8 - HD GC B cells")
)
```






