---
title: "Post_CellTypist_MiloPrep"
output: html_document
date: "2023-01-01"
---

# Libraries
```{r}
library(Seurat)
library(SeuratDisk)
library(anndata)
library(zellkonverter)
library(ggplot2)
library(scran)
library(scater)
options(future.globals.maxSize=1000000000000000) # Set max global size so we don't run out of memory
```
# Load in AnnData H5 object and convert to Seurat object
```{r}
base.object <- readRDS("/Users/gagled01/morganLab/Waldenstroms/singlecell/WM_Prelim_RNAonly_Merged.rds")
h5 <- readH5AD("/Users/gagled01/morganLab/Waldenstroms/singlecell/WM_Prelim_CelltypistAnnotated_Object.h5ad", verbose = TRUE)
seurat.object <- as.Seurat(h5, counts = "X", data = NULL)
saveRDS(seurat.object, "/Users/gagled01/morganLab/Waldenstroms/singlecell/WM_Prelim_RNAonly_CellTypistAnnotated.rds")
DimPlot(seurat.object, group.by = "majority_voting")
```
# Fix possible cell mismatches and assign new celltype variables
```{r}
# Fixing cell mismatch. Idk where it came from
mismatch <- setdiff(rownames(seurat.object@meta.data), rownames(base.object@meta.data))
seurat.object <- seurat.object[,!colnames(seurat.object) %in% mismatch]

base.object@meta.data$majority_voting_low2 <- seurat.object@meta.data$majority_voting
base.object@meta.data$conf_score_low2 <- seurat.object@meta.data$conf_score
base.object@meta.data$predicted_labels_low2 <- seurat.object@meta.data$predicted_labels

table(base.object@meta.data$majority_voting_low2)
table(base.object@meta.data$majority_voting_low)
```
# Save it out
```{r}
saveRDS(base.object, "/Users/gagled01/morganLab/single-cell/CITE_Study/objects/T1_Bcells_10PCs_MiloPrelimAnalysis_Subset_CellTypistLow.rds")
```
# Set object
```{r}
cite <- base.object
table(cite@meta.data$majority_voting_low2)
```
```{r}
cite <- readRDS("/Users/gagled01/morganLab/single-cell/CITE_Study/objects/T2_Bcells_MiloPrelimAnalysis_Subset_CellTypistLow.rds")
```

# Run standard workflow. Use # PCs ~equal to number of CellTypist identified populations
```{r}
cite <- NormalizeData(cite, normalization.method = "LogNormalize", scale.factor = 10000)
cite <- FindVariableFeatures(cite, selection.method = "vst", nfeatures = 2000)
cite <- ScaleData(cite)
cite <- RunPCA(cite, npcs = 15, reduction.name = "overestimated_pca")
ElbowPlot(
  object = cite, 
  ndims = 15
) +
  geom_abline(
    aes(intercept = 2.45, slope = 0, color = "red"),
    show.legend = FALSE
  )
ggsave('/Users/gagled01/morganLab/single-cell/CITE_Study/figures/T2_Bcells_13PCs_ElbowPlot_MiloPrelimAnalysis_Subset_CellTypistLow.png')
```
```{r}
# Determine percent of variation associated with each PC
pct <- seurat_integrated[["pca"]]@stdev / sum(seurat_integrated[["pca"]]@stdev) * 100

# Calculate cumulative percents for each PC
cumu <- cumsum(pct)

# Determine which PC exhibits cumulative percent greater than 90% and % variation associated with the PC as less than 5
co1 <- which(cumu > 90 & pct < 5)[1]

co1

# Determine the difference between variation of PC and subsequent PC
co2 <- sort(which((pct[1:length(pct) - 1] - pct[2:length(pct)]) > 0.1), decreasing = T)[1] + 1

# last point where change of % of variation is more than 0.1%.
co2

# Minimum of the two calculation
pcs <- min(co1, co2)

pcs
```

```{r}
cite <- RunPCA(cite, npcs = 13)
cite <- FindNeighbors(cite, dims = 1:13)
cite <- FindClusters(cite, resolution = 0.2)
cite <- RunUMAP(cite, dims = 1:13)
#DimPlot(cite, label = T, reduction = "umap", group.by = "majority_voting_low2")
#DimPlot(cite, label = T, reduction = "umap", group.by = "seurat_clusters")
table(cite@meta.data$majority_voting_low2)
```
# Convert to SCE and make dim plots cuz they look nicer than Seurat
```{r}
sce <- as.SingleCellExperiment(cite)

plotReducedDim(sce, "UMAP", colour_by = "majority_voting_low2")
ggsave('/Users/gagled01/morganLab/single-cell/CITE_Study/figures/T1_Bcells_10PCs_MiloPrelimAnalysis_Subset_CellTypistLow_UMAP.png')
plotReducedDim(sce, "UMAP", colour_by = "patient")
ggsave('/Users/gagled01/morganLab/single-cell/CITE_Study/figures/T1_Bcells_10PCs_MiloPrelimAnalysis_Subset_UMAP.png')

# cite.sub <- subset(cite, subset = majority_voting_low == "Tem/Temra cytotoxic T cells")
# sce.sub <- as.SingleCellExperiment(cite)
# plotReducedDim(sce.sub, "UMAP", colour_by = "majority_voting_low")
# ggsave('/Users/gagled01/morganLab/single-cell/CITE_Study/figures/Dara_T1_Bcells_10PCsubset_CellTypistLow_UMAP_BcellssRemoved.png')
```
# Save it out again. Ready for Milo
```{r}
saveRDS(cite, "/Users/gagled01/morganLab/single-cell/CITE_Study/objects/T1_NKcells_10PCs_MiloPrelimAnalysis_Subset_CellTypistLow_MiloReady.rds")
```


