---
title: "Second_TRUST4_AnnotationAttempt"
output: html_document
date: "2023-11-21"
---

Load libraries etc.
```{r}
library(Seurat)
library(ggplot2)
library(ArchR)
library(dplyr)
library(immunarch)
library(BSgenome.Hsapiens.UCSC.hg38)
addArchRThreads(threads = 1)
addArchRGenome("hg38")
options(future.globals.maxSize=10000000000000000) 
```
Load in ArchR object
```{r}
archR <- loadArchRProject(path = "WM_2024_PeaksChromVar")
```
Load aggregated TRUST4 BCR data bam reports
```{r}
library(immunarch)
wm <- repLoad("/Users/gagled01/morganLab/Waldenstroms/TRUST4_working/outputs/bam_reports")
wm$data[[12]]
```
And Immunarch style reports (also TRUST4 outputs)
```{r}
# Load barcode files
p01_076_barcodes <- read.table("/Users/gagled01/morganLab/Waldenstroms/TRUST4_working/outputs/barcode_reports/TRUST_01-076_gex_possorted_bam_barcode_airr.tsv", sep = "\t", header = T)
p01_115_barcodes <- read.table("/Users/gagled01/morganLab/Waldenstroms/TRUST4_working/outputs/barcode_reports/TRUST_01-115_gex_possorted_bam_barcode_airr.tsv", sep = "\t", header = T)
p01_131_barcodes <- read.table("/Users/gagled01/morganLab/Waldenstroms/TRUST4_working/outputs/barcode_reports/TRUST_01-131_gex_possorted_bam_barcode_airr.tsv", sep = "\t", header = T)
p01_163_barcodes <- read.table("/Users/gagled01/morganLab/Waldenstroms/TRUST4_working/outputs/barcode_reports/TRUST_01-163_gex_possorted_bam_barcode_airr.tsv", sep = "\t", header = T)
p01_190_barcodes <- read.table("/Users/gagled01/morganLab/Waldenstroms/TRUST4_working/outputs/barcode_reports/TRUST_01-190_gex_possorted_bam_barcode_airr.tsv", sep = "\t", header = T)
p04_003_barcodes <- read.table("/Users/gagled01/morganLab/Waldenstroms/TRUST4_working/outputs/barcode_reports/TRUST_04-003_gex_possorted_bam_barcode_airr.tsv", sep = "\t", header = T)
p04_006_barcodes <- read.table("/Users/gagled01/morganLab/Waldenstroms/TRUST4_working/outputs/barcode_reports/TRUST_04-006_gex_possorted_bam_barcode_airr.tsv", sep = "\t", header = T)
wm25_barcodes <- read.table("/Users/gagled01/morganLab/Waldenstroms/TRUST4_working/outputs/barcode_reports/TRUST_WM25_gex_possorted_bam_barcode_airr.tsv", sep = "\t", header = T)
wm43_barcodes <- read.table("/Users/gagled01/morganLab/Waldenstroms/TRUST4_working/outputs/barcode_reports/TRUST_WM43_gex_possorted_bam_barcode_airr.tsv", sep = "\t", header = T)
wm46_barcodes <- read.table("/Users/gagled01/morganLab/Waldenstroms/TRUST4_working/outputs/barcode_reports/TRUST_WM46_gex_possorted_bam_barcode_airr.tsv", sep = "\t", header = T)
wm47_barcodes <- read.table("/Users/gagled01/morganLab/Waldenstroms/TRUST4_working/outputs/barcode_reports/TRUST_WM47_gex_possorted_bam_barcode_airr.tsv", sep = "\t", header = T)
wm54_barcodes <- read.table("/Users/gagled01/morganLab/Waldenstroms/TRUST4_working/outputs/barcode_reports/TRUST_WM54_gex_possorted_bam_barcode_airr.tsv", sep = "\t", header = T)
wm65_barcodes <- read.table("/Users/gagled01/morganLab/Waldenstroms/TRUST4_working/outputs/barcode_reports/TRUST_WM65_gex_possorted_bam_barcode_airr.tsv", sep = "\t", header = T)
```
Check patient barcodes match
```{r}
cell_id_fixed <- gsub("0.-..._", "", archR$cellNames_clean)
archR$cell_id_fixed <- cell_id_fixed
cell_id_fixed2 <- gsub("-1", "", archR$cell_id_fixed)
archR$cell_id_fixed <- cell_id_fixed2
cell_id_fixed3 <- gsub("WM..", "", archR$cell_id_fixed)
archR$cell_id_fixed <- cell_id_fixed3

# Wait actually need this
patient_barcode <- gsub("-1$", "", archR$cellNames_clean) # need to use $ to specify end of string bcuz otherwise the -1 in 01-115 (and the 3 other patients like this) will get replaced!!! 
archR$patient_barcode_clean <- patient_barcode
```
# Fixing TRUST4 barcodes in the TRUST4 output for each patient
```{r}
# Fix cell ids
p01_076_barcodes$cell_id_fixed <- gsub("-1", "", p01_076_barcodes$cell_id) # remove the -1
p01_076_barcodes$patient_barcode_clean <- paste0("01-076_", p01_076_barcodes$cell_id_fixed) # add the patient as prefix. if you do not fix cell types like this you run the risk of overmatching due to NON-UNIQUENESS OF CELL BARCODES between patients
p01_076_barcodes$sample <- "01-076"

p01_115_barcodes$cell_id_fixed <- gsub("-1$", "", p01_115_barcodes$cell_id)
p01_115_barcodes$patient_barcode_clean <- paste0("01-115_", p01_115_barcodes$cell_id_fixed)
p01_115_barcodes$sample <- "01-115"

p01_131_barcodes$cell_id_fixed <- gsub("-1$", "", p01_131_barcodes$cell_id)
p01_131_barcodes$patient_barcode_clean <- paste0("01-131_", p01_131_barcodes$cell_id_fixed)
p01_131_barcodes$sample <- "01-131"

p01_163_barcodes$cell_id_fixed <- gsub("-1$", "", p01_163_barcodes$cell_id)
p01_163_barcodes$patient_barcode_clean <- paste0("01-163_", p01_163_barcodes$cell_id_fixed)
p01_163_barcodes$sample <- "01-163"

p01_190_barcodes$cell_id_fixed <- gsub("-1$", "", p01_190_barcodes$cell_id)
p01_190_barcodes$patient_barcode_clean <- paste0("01-190_", p01_190_barcodes$cell_id_fixed)
p01_190_barcodes$sample <- "01-190"

p04_003_barcodes$cell_id_fixed <- gsub("-1$", "", p04_003_barcodes$cell_id)
p04_003_barcodes$patient_barcode_clean <- paste0("04-003_", p04_003_barcodes$cell_id_fixed)
p04_003_barcodes$sample <- "04-003"

p04_006_barcodes$cell_id_fixed <- gsub("-1$", "", p04_006_barcodes$cell_id)
p04_006_barcodes$patient_barcode_clean <- paste0("04-006_", p04_006_barcodes$cell_id_fixed)
p04_006_barcodes$sample <- "04-006"

wm25_barcodes$cell_id_fixed <- gsub("-1$", "", wm25_barcodes$cell_id)
wm25_barcodes$patient_barcode_clean <- paste0("WM25_", wm25_barcodes$cell_id_fixed)
wm25_barcodes$sample <- "WM25"

wm43_barcodes$cell_id_fixed <- gsub("-1$", "", wm43_barcodes$cell_id)
wm43_barcodes$patient_barcode_clean <- paste0("WM43_", wm43_barcodes$cell_id_fixed)
wm43_barcodes$sample <- "WM43"

wm46_barcodes$cell_id_fixed <- gsub("-1$", "", wm46_barcodes$cell_id)
wm46_barcodes$patient_barcode_clean <- paste0("WM46_", wm46_barcodes$cell_id_fixed)
wm46_barcodes$sample <- "WM46"

wm47_barcodes$cell_id_fixed <- gsub("-1$", "", wm47_barcodes$cell_id)
wm47_barcodes$patient_barcode_clean <- paste0("WM47_", wm47_barcodes$cell_id_fixed)
wm47_barcodes$sample <- "WM47"

wm54_barcodes$cell_id_fixed <- gsub("-1$", "", wm54_barcodes$cell_id)
wm54_barcodes$patient_barcode_clean <- paste0("WM54_", wm54_barcodes$cell_id_fixed)
wm54_barcodes$sample <- "WM54"

wm65_barcodes$cell_id_fixed <- gsub("-1$", "", wm65_barcodes$cell_id)
wm65_barcodes$patient_barcode_clean <- paste0("WM65_", wm65_barcodes$cell_id_fixed)
wm65_barcodes$sample <- "WM65"

length(intersect(archR$patient_barcode_clean, p01_076_barcodes$patient_barcode_clean)) # they all match nice
length(intersect(archR$patient_barcode_clean, p01_115_barcodes$patient_barcode_clean)) 
length(intersect(archR$patient_barcode_clean, p01_131_barcodes$patient_barcode_clean)) 
length(intersect(archR$patient_barcode_clean, p01_163_barcodes$patient_barcode_clean)) 
length(intersect(archR$patient_barcode_clean, p01_190_barcodes$patient_barcode_clean)) 
length(intersect(archR$patient_barcode_clean, p04_003_barcodes$patient_barcode_clean))
length(intersect(archR$patient_barcode_clean, p04_006_barcodes$patient_barcode_clean))
length(intersect(archR$patient_barcode_clean, wm25_barcodes$patient_barcode_clean))
length(intersect(archR$patient_barcode_clean, wm43_barcodes$patient_barcode_clean))
length(intersect(archR$patient_barcode_clean, wm46_barcodes$patient_barcode_clean))
length(intersect(archR$patient_barcode_clean, wm47_barcodes$patient_barcode_clean))
length(intersect(archR$patient_barcode_clean, wm54_barcodes$patient_barcode_clean))
length(intersect(archR$patient_barcode_clean, wm65_barcodes$patient_barcode_clean))

# Merge into single df
all_barcodes <- rbind(p01_076_barcodes, p01_115_barcodes, p01_131_barcodes, p01_163_barcodes,p01_190_barcodes, p04_003_barcodes, p04_006_barcodes,
                      wm25_barcodes, wm43_barcodes, wm46_barcodes, wm47_barcodes, wm54_barcodes, wm65_barcodes)

all_barcodes
wm54_barcodes
```
Annotate ArchR data with TRUST4 info on a per patient basis
```{r}
archR$topCDR3s <- NA
archR$hasTopCDR3 <- "No"

wm$data[[1]]
p01_076.cells.with <- all_barcodes$patient_barcode_clean[all_barcodes$junction_aa == "CQQFDSSWTF"]
length(intersect(p01_076.cells.with, archR$patient_barcode_clean))
archR$topCDR3s[archR$patient_barcode_clean %in% p01_076.cells.with] <- "CQQFDSSWTF"
archR$hasTopCDR3[archR$patient_barcode_clean %in% p01_076.cells.with] <- "Yes"
table(archR$topCDR3s)
table(archR$hasTopCDR3)

wm$data[[2]]
p01_115.cells.with <- all_barcodes$patient_barcode_clean[all_barcodes$junction_aa == "CLQRGNWPLTF"]
length(intersect(p01_115.cells.with, archR$patient_barcode_clean))
archR$topCDR3s[archR$patient_barcode_clean %in% p01_115.cells.with] <- "CLQRGNWPLTF"
archR$hasTopCDR3[archR$patient_barcode_clean %in% p01_115.cells.with] <- "Yes"
table(archR$topCDR3s)
table(archR$hasTopCDR3)


wm$data[[3]]
p01_131.cells.with <- all_barcodes$patient_barcode_clean[all_barcodes$junction_aa == "CQQYYSIPTF"]
length(intersect(p01_131.cells.with, archR$patient_barcode_clean))
archR$topCDR3s[archR$patient_barcode_clean %in% p01_131.cells.with] <- "CQQYYSIPTF"
archR$hasTopCDR3[archR$patient_barcode_clean %in% p01_131.cells.with] <- "Yes"
table(archR$topCDR3s)
table(archR$hasTopCDR3)

wm$data[[4]]
p01_163.cells.with <- all_barcodes$patient_barcode_clean[all_barcodes$junction_aa == "CQQYNNWPPLTF"]
length(intersect(p01_163.cells.with, archR$patient_barcode_clean))
archR$topCDR3s[archR$patient_barcode_clean %in% p01_163.cells.with] <- "CQQYNNWPPLTF"
archR$hasTopCDR3[archR$patient_barcode_clean %in% p01_163.cells.with] <- "Yes"
table(archR$topCDR3s)
table(archR$hasTopCDR3)

wm$data[[5]]
p01_190.cells.with <- all_barcodes$patient_barcode_clean[all_barcodes$junction_aa == "CQQYNNWPITF"]
length(intersect(p01_190.cells.with, archR$patient_barcode_clean))
archR$topCDR3s[archR$patient_barcode_clean %in% p01_190.cells.with] <- "CQQYNNWPITF"
archR$hasTopCDR3[archR$patient_barcode_clean %in% p01_190.cells.with] <- "Yes"
table(archR$topCDR3s)
table(archR$hasTopCDR3)

wm$data[[6]]
p04_003.cells.with <- all_barcodes$patient_barcode_clean[all_barcodes$junction_aa == "CQQYDSYPYTF"]
length(intersect(p04_003.cells.with, archR$patient_barcode_clean))
archR$topCDR3s[archR$patient_barcode_clean %in% p04_003.cells.with] <- "CQQYDSYPYTF"
archR$hasTopCDR3[archR$patient_barcode_clean %in% p04_003.cells.with] <- "Yes"
table(archR$topCDR3s)
table(archR$hasTopCDR3)

wm$data[[7]]
p04_006.cells.with <- all_barcodes$patient_barcode_clean[all_barcodes$junction_aa == "CQQYGTSSLTF"]
length(intersect(p04_006.cells.with, archR$patient_barcode_clean))
archR$topCDR3s[archR$patient_barcode_clean %in% p04_006.cells.with] <- "CQQYGTSSLTF"
archR$hasTopCDR3[archR$patient_barcode_clean %in% p04_006.cells.with] <- "Yes"
table(archR$topCDR3s)
table(archR$hasTopCDR3)

wm$data[[8]]
wm25.cells.with <- all_barcodes$patient_barcode_clean[all_barcodes$junction_aa == "CMQALQTPRTF"]
length(intersect(wm25.cells.with, archR$patient_barcode_clean))
archR$topCDR3s[archR$patient_barcode_clean %in% wm25.cells.with] <- "CMQALQTPRTF"
archR$hasTopCDR3[archR$patient_barcode_clean %in% wm25.cells.with] <- "Yes"
table(archR$topCDR3s)
table(archR$hasTopCDR3)

wm$data[[9]]
wm43.cells.with <- all_barcodes$patient_barcode_clean[all_barcodes$junction_aa == "CQQYNTYPWTF"]
length(intersect(wm43.cells.with, archR$patient_barcode_clean))
archR$topCDR3s[archR$patient_barcode_clean %in% wm43.cells.with] <- "CQQYNTYPWTF"
archR$hasTopCDR3[archR$patient_barcode_clean %in% wm43.cells.with] <- "Yes"
table(archR$topCDR3s)
table(archR$hasTopCDR3)

wm$data[[10]]
wm46.cells.with <- all_barcodes$patient_barcode_clean[all_barcodes$junction_aa == "CQQYNNWPRTF"]
length(intersect(wm46.cells.with, archR$patient_barcode_clean))
archR$topCDR3s[archR$patient_barcode_clean %in% wm46.cells.with] <- "CQQYNNWPRTF"
archR$hasTopCDR3[archR$patient_barcode_clean %in% wm46.cells.with] <- "Yes"
table(archR$topCDR3s)
table(archR$hasTopCDR3)

wm$data[[11]]
wm47.cells.with <- all_barcodes$patient_barcode_clean[all_barcodes$junction_aa == "CQQYGSSSSYTF"]
length(intersect(wm47.cells.with, archR$patient_barcode_clean))
archR$topCDR3s[archR$patient_barcode_clean %in% wm47.cells.with] <- "CQQYGSSSSYTF"
archR$hasTopCDR3[archR$patient_barcode_clean %in% wm47.cells.with] <- "Yes"
table(archR$topCDR3s)
table(archR$hasTopCDR3)

wm$data[[12]]
wm54.cells.with <- all_barcodes$patient_barcode_clean[all_barcodes$junction_aa == "CQQCGDWPLTF"]
length(intersect(wm54.cells.with, archR$patient_barcode_clean))
archR$topCDR3s[archR$patient_barcode_clean %in% wm54.cells.with] <- "CQQCGDWPLTF"
archR$hasTopCDR3[archR$patient_barcode_clean %in% wm54.cells.with] <- "Yes"
table(archR$topCDR3s)
table(archR$hasTopCDR3)

wm$data[[13]]
wm65.cells.with <- all_barcodes$patient_barcode_clean[all_barcodes$junction_aa == "CQQYNSYPYTF"]
length(intersect(wm65.cells.with, archR$patient_barcode_clean))
archR$topCDR3s[archR$patient_barcode_clean %in% wm65.cells.with] <- "CQQYNSYPYTF"
archR$hasTopCDR3[archR$patient_barcode_clean %in% wm65.cells.with] <- "Yes"
table(archR$topCDR3s)
table(archR$hasTopCDR3)

p1 <- plotEmbedding(archR, embedding = "BLineage_Recluster_UMAP", name = "topCDR3s")
p2 <- plotEmbedding(archR, embedding = "BLineage_Recluster_UMAP", name = "hasTopCDR3")

plotPDF(p1, p2, name = "Blineage_Recluster_TopCDR3_UMAP", width = 5, height = 5, ArchRProj = archR, addDOC = FALSE)
```
SAVE IT OUT!
```{r}
saveArchRProject(ArchRProj = archR, outputDirectory = "WM_2024_PeaksChromVarTRUST4", load = F)
```


