---
title: "WM_FinalBatchEffectFix"
output: html_document
date: "2024-08-27"
---

```{r}
library(ArchR)
library(Seurat)
library(SummarizedExperiment)
addArchRThreads(threads = 1)
addArchRGenome("hg38")
options(future.globals.maxSize=1000000000000000000000000000) 
archR <- loadArchRProject(path = "/Users/gagled01/morganLab/Waldenstroms/singlecell/data/ATAC_fragments/WM_DeviationsAdded")
```

```{r}
archR <- addHarmony(
  archR,
  reducedDims = "IterativeLSI_BLineage_Recluster_NoProgens",
  name = "FinalHarmony",
  groupBy = "batch"
)

archR <- addUMAP(
    ArchRProj = archR, 
    reducedDims = "FinalHarmony", 
    name = "UMAP_Harmony", 
    nNeighbors = 30, 
    minDist = 0.5, 
    metric = "cosine",
    force = T
)

archR <- addClusters(
  input = archR,
  reducedDims = "FinalHarmony",
  method = "Seurat",
  name = "FinalHarmony_Clusters",
  resolution = 0.8,
  force = TRUE
)
```
# Generate new annotation without intermediates
```{r}
archR$final_annotation <- archR$tripartite_annotation
archR$final_annotation[archR$tripartite_annotation == "Intermediate MBC" & archR$samplesClean == "WM25"] <- "PC-like MBC" # convert other intermediates to PC-like
archR$final_annotation[archR$tripartite_annotation == "Intermediate MBC" & archR$samplesClean == "WM54"] <- "PC-like MBC"

# Confirm ID of secondary cluster MBCs
archR$final_annotation[archR$FinalHarmony_Clusters == "C5"] <- "MBC-like MBC"
archR$final_annotation[archR$FinalHarmony_Clusters == "C6"] <- "MBC-like MBC"
archR$final_annotation[archR$FinalHarmony_Clusters == "C15"] <- "MBC-like MBC" # this is the WM54 secondary clone...so 1 clone is PC-like and the other is MBC-like???

# Specify PC other clonal and non-clonalpopulations
archR$final_annotation[archR$tripartite_annotation == "Clonal PCs"] <- "Monoclonal PC" # fix name
archR$final_annotation[archR$FinalHarmony_Clusters == "C3"] <- "Polyclonal PC"
archR$final_annotation[archR$final_annotation == "Non-clonal MBC"] <- "Polyclonal MBC"

# set WM43 as the 1 true intermediate
archR$final_annotation[archR$samplesClean == "WM43" & archR$FinalHarmony_Clusters == "C5"] <- "WM43" 

table(archR$final_annotation)

cols <- table(archR$final_annotation)
names(cols) <- names(table(archR$final_annotation)) 
cols[1] <- "lightseagreen"
cols[2] <- "forestgreen"
cols[3] <- "firebrick"
cols[4] <- "thistle2"
cols[5] <- "orange"
cols[6] <- "slateblue"
cols[7] <- "darkmagenta"
cols[8] <- "goldenrod"
cols[9] <- "black"
cols[10] <- "darkcyan"
  
plotEmbedding(ArchRProj = archR, colorBy = "cellColData", name = "final_annotation", embedding = "UMAP_Harmony", pal = cols, labelAsFactors = TRUE)
plotEmbedding(ArchRProj = archR, colorBy = "cellColData", name = "samplesClean", embedding = "UMAP_Harmony")
plotEmbedding(ArchRProj = archR, colorBy = "cellColData", name = "hasTopCDR3", embedding = "UMAP_Harmony")

```

```{r}
# Save out
saveArchRProject(ArchRProj = archR, outputDirectory = "WM_DeviationsAdded_BatchCorrected", load = F)
```

