---
title: "WM_CNVs"
output: html_document
date: "2024-05-23"
---

```{r}
library(GenVisR)
library("stringr")

# get locations of all cn files
files <- list.files("/Users/gagled01/Downloads/temp", full.names = TRUE)

# create function to read in and format data
a <- function(x){
    # read data and set column names
    data <- read.delim(x, header=FALSE)
    colnames(data) <- c("chromosome", "start", "end", "probes", "segmean")

    # get the sample name from the file path
    sampleName <- str_extract(x, "H_OM.+cc2")
    sampleName <- gsub(".cc2", "", sampleName)
    data$sample <- sampleName

    # return the data
    return(data)
}

# run the anonymous function defined above
cnData <- lapply(files, a)

# turn the list of data frames into a single data frame
cnData <- do.call("rbind", cnData)
cnData

cnFreq(cnData, genome="hg19")


batten.temp <- read.table("/Users/gagled01/morganLab/Waldenstroms/WGS/cnvs/04-006_B_S8_001_subclones.txt", header = T)
batten.temp$segmean <- batten.temp$nMaj1_A + batten.temp$nMin1_A
batten.df <- data.frame(chromosome=batten.temp$chr, start=batten.temp$startpos, end=batten.temp$endpos, segmean=batten.temp$segmean, sample=rep("04-006", length(batten.temp$chr)))

cnFreq(batten.df, genome = "hg38")

facets.temp <- read.table("/Users/gagled01/morganLab/Waldenstroms/WGS/cnvs/04-006_B_S8_001_vs_04-006_T_S21_001.facets.cnv.txt", header = T)

head(batten.temp)
head(facets.temp)
head(cnData)

batten.temp[batten.temp$chr == "chr2",]

```
```{r}
library(GenVisR)
# Stage bed files
files <- list.files("/Users/gagled01/morganLab/Waldenstroms/WGS/cnvs/battenberg_beds", full.names = TRUE)

temp <- read.table(files[2], sep = "\t", header = T)

# Function to read bed file and convert to df
read.battenberg <- function(x){
    # read data and set column names
    data <- read.table(x, sep = "\t", header=TRUE)
    a <- unlist(strsplit(x, "beds/"))[2]
    samplename <- gsub("\\_.*", "", a)
    print(samplename)
    
    data.df <- data.frame(chromosome=data$seqnames, start=data$start, end=data$end, segmean=data$total_cn_nonrounded, sample=rep(samplename, length(data$seqnames)))
    data.

    # return the data
    return(data.df)
}

# Run function on all files
cnData <- lapply(files, read.battenberg)

# Turn the list of data frames into a single data frame
cnData <- do.call("rbind", cnData)
cnData



# Run it
cnFreq(cnData, genome="hg38", CN_high_cutoff = 2.5)
cnFreq(cnData, genome="hg38", CN_high_cutoff = 2.8)

read.battenberg(files[1])

hist(cnData$segmean)
```
```{r}
cnv.csv <- read.csv("/Users/gagled01/morganLab/Waldenstroms/wmWgsMetadata_CNVshit_FakeTreat.csv")
head(cnv.csv)
table(cnv.csv$del.6q)

chisq.test(cnv.csv$del.6q, cnv.csv$Subtype)

```


