---
title: "WM_SurvivalAnalysis"
output: html_document
date: "2024-05-28"
---

# Load libraries and data
```{r}
library(survival)
library(ggsurvfit)
library(ggplot2)
library(tidyr)
library(dplyr)

dat <- read.table("/Users/gagled01/morganLab/Waldenstroms/ClinicalData/WM_ClinicalData_forStats.csv", sep = ",", header = TRUE)
colnames(dat)[1] <- "PATIENT"
dat <- dat[dat$SUBTYPE %in% c("PC-LIKE", "MBC-LIKE"),]

# Subsetting df to include only patients we are interested in for p-value calculations (so these are patients with either WGS and/or subtype annotations scRNA)
# This ends up being the 32 patients with WGS + scRNA or bulk PLUS the 2 scRNA patients without WGS (WM25 and 04-003)
dat.wgs.patients <- dat$PATIENT[dat$WGS == 1] # patients with WGS
dat.bonus.scrna.patients <- dat$PATIENT[dat$PATIENT %in% c("WM25", "04-003")] # extra patients with scRNA
core34.patients <- c(dat.wgs.patients, dat.bonus.scrna.patients) # combine

dat.core34 <- dat[dat$PATIENT %in% core34.patients] # subset by this patient list
```
# Overall Survival curve
```{r}
p <- survfit2(Surv(Time.OS, Status.Death) ~ SUBTYPE, data = dat.core34) |>
  ggsurvfit(linewidth = 1) +
  add_confidence_interval() +
  add_risktable() +
  add_quantile(y_value = 0.6, color = "gray50", linewidth = 0.75) +
  scale_ggsurvfit()
p +
  # limit plot to show 8 years and less
  #coord_cartesian(xlim = c(0, 8)) +
  # update figure labels/titles
  labs(
    y = "Percentage Survival",
    x = "Time (months)",
    title = "Overall Survival",
  ) + theme(plot.title = element_text(size = 14, hjust = 0.5, face = "bold"))
ggsave("/Users/gagled01/morganLab/Waldenstroms/scRNA_ATAC/figures/Supplementary/SuppFigure_OS_Curve.pdf", height = 8, width = 12)
```
# Other curves - TTFT, TTNT, PFS
```{r}
# Time to first treatment
p <- survfit2(Surv(Time.TTFT, Status) ~ Subtype, data = dat) |>
  ggsurvfit(linewidth = 1) +
  add_confidence_interval() +
  add_risktable() +
  add_quantile(y_value = 0.6, color = "gray50", linewidth = 0.75) +
  scale_ggsurvfit()

pdf(file = "/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Supplementary/SuppFigure23_TTFT_Curve.pdf", height = 8, width = 8)
p +
  # limit plot to show 8 years and less
  #coord_cartesian(xlim = c(0, 8)) +
  # update figure labels/titles
  labs(
    y = "Percentage Treated",
    x = "Time (months)",
    title = "Time to First Treatment",
  ) + theme(plot.title = element_text(size = 14, hjust = 0.5, face = "bold"))
dev.off()

# PFS/EFS
p <- survfit2(Surv(Time.PFS.EFS, Status) ~ SUBTYPE, data = dat) |>
  ggsurvfit(linewidth = 1) +
  add_confidence_interval() +
  add_risktable() +
  add_quantile(y_value = 0.6, color = "gray50", linewidth = 0.75) +
  scale_ggsurvfit()

pdf(file = "/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Supplementary/SuppFigure23_PFS_EFS_Curve.pdf", height = 8, width = 8)
p +
  # limit plot to show 8 years and less
  #coord_cartesian(xlim = c(0, 8)) +
  # update figure labels/titles
  labs(
    y = "Percentage Survival",
    x = "Time (months)",
    title = "Progression Free Survival",
  ) + theme(plot.title = element_text(size = 14, hjust = 0.5, face = "bold"))
dev.off()

# Time to next treatment
p <- survfit2(Surv(Time.TTNT, Status) ~ Subtype, data = dat) |>
  ggsurvfit(linewidth = 1) +
  add_confidence_interval() +
  add_risktable() +
  add_quantile(y_value = 0.6, color = "gray50", linewidth = 0.75) +
  scale_ggsurvfit()

pdf(file = "/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Supplementary/SuppFigure23_TTNT_Curve.pdf", height = 8, width = 8)
p +
  # limit plot to show 8 years and less
  #coord_cartesian(xlim = c(0, 8)) +
  # update figure labels/titles
  labs(
    y = "Percentage Treated",
    x = "Time (months)",
    title = "Time to Next Treatment",
  ) + theme(plot.title = element_text(size = 14, hjust = 0.5, face = "bold"))
dev.off()
```
# Clinical analysis and table generation

# Collect median values and %s for table
```{r}
# Remove top row which is NA
#dat <- dat[-1,]

# Subset by subtype
mbc.dat.core34 <- dat.core34[dat.core34$SUBTYPE == "MBC-LIKE",]
pc.dat.core34 <- dat.core34[dat.core34$SUBTYPE %in% c("PC-LIKE"),]

# Drop NAs more
#mbc.dat.core34 <- mbc.dat.core34 %>% drop_na(PATIENT)
mbc.age <- median(mbc.dat.core34$AGE.DIAG, na.rm = T)
pc.age <- median(pc.dat.core34$AGE.DIAG, na.rm = T)

range(pc.dat.core34$AGE.DIAG, na.rm = T)

# IgM
mbc.igm <- median(as.numeric(mbc.dat.core34$IgM.New), na.rm = TRUE)
pc.igm <- median(as.numeric(pc.dat.core34$IgM.New), na.rm = TRUE)

# % Infiltration
mbc.infilt <- median(as.numeric(mbc.dat.core34$DIAG.INFILT), na.rm = TRUE)
pc.infilt <- median(as.numeric(pc.dat.core34$DIAG.INFILT), na.rm = TRUE)

# Hemoglobin
mbc.hemo <- median(as.numeric(mbc.dat.core34$DIAG.HB), na.rm = TRUE)
pc.hemo <- median(as.numeric(pc.dat.core34$DIAG.HB), na.rm = TRUE)

# Platelets
mbc.plat <- median(as.numeric(mbc.dat.core34$DIAG.PLAT), na.rm = TRUE)
pc.plat <- median(as.numeric(pc.dat.core34$DIAG.PLAT), na.rm = TRUE)

# % patients with spleen enlargement
mbc.spln <- as.numeric(table(as.numeric(mbc.dat.core34$DIAG.SPM))[2]/sum(table(mbc.dat.core34$DIAG.SPM)))*100
pc.spln <- as.numeric(table(as.numeric(pc.dat.core34$DIAG.SPM))[2]/sum(table(pc.dat.core34$DIAG.SPM)))*100

# % patients with enlarged lymph nodes
mbc.lymph <- as.numeric(table(as.numeric(mbc.dat.core34$DIAG.ADNP))[2]/sum(table(mbc.dat.core34$DIAG.ADNP)))*100
pc.lymph <- as.numeric(table(as.numeric(pc.dat.core34$DIAG.ADNP))[2]/sum(table(pc.dat.core34$DIAG.ADNP)))*100

# % patients with elevated LDH
mbc.ldh <- as.numeric(table(as.numeric(mbc.dat.core34$DIAG.LDH))[2]/sum(table(mbc.dat.core34$DIAG.LDH)))*100
pc.ldh <- as.numeric(table(as.numeric(pc.dat.core34$DIAG.LDH))[2]/sum(table(pc.dat.core34$DIAG.LDH)))*100

# Median OS
mbc.os <- median(as.numeric(mbc.dat.core34$Time.OS), na.rm = TRUE)
pc.os <- median(as.numeric(pc.dat.core34$Time.OS), na.rm = TRUE)

# Median PFS
mbc.pfs <- median(as.numeric(mbc.dat.core34$Time.PFS.EFS), na.rm = TRUE)
pc.pfs <- median(as.numeric(pc.dat.core34$Time.PFS.EFS), na.rm = TRUE)

# combine values by subtype
mbc.values <- round(c(mbc.age, mbc.infilt, mbc.spln, mbc.lymph, mbc.igm, mbc.hemo, mbc.plat, mbc.ldh, mbc.os), digits = 1)
mbc.values <- append("10", mbc.values)
pc.values <- round(c(pc.age, pc.infilt, pc.spln, pc.lymph, pc.igm, pc.hemo, pc.plat, pc.ldh, pc.os), digits = 1)
pc.values <- append("23", pc.values)

# Try t-test
# igm.ttest <- t.test(as.numeric(dat.core34$DIAG.IgM) ~ as.character(dat.core34$SUBTYPE), alternative = "two.sided")
# infilt.ttest <- t.test(as.numeric(dat.core34$DIAG.INFILT) ~ as.character(dat.core34$SUBTYPE), alternative = "two.sided")
# hemo.ttest <- t.test(as.numeric(dat.core34$DIAG.HB) ~ as.character(dat.core34$SUBTYPE), alternative = "two.sided")
# plat.ttest <- t.test(as.numeric(dat.core34$DIAG.PLAT) ~ as.character(dat.core34$SUBTYPE), alternative = "two.sided")
# 
# chisq.test(dat.core34$DIAG.SPM, dat.core34$SUBTYPE)[3]
# chisq.test(dat.core34$DIAG.ADNP, dat.core34$SUBTYPE)
# chisq.test(dat.core34$DIAG.LDH, dat.core34$SUBTYPE)

# make df 
clin.df <- as.data.frame(matrix(ncol = 3, nrow = 10))
colnames(clin.df) <- c("Variable", "MBC-like", "PC-like")
#rownames(clin.df) <- c("Number of patients", "IgM (g/dL)", "BM Infiltration (%)", "Hemoglobin (g/dL)", "Platelets (g/L)", "Spleen Enlargement (% patients)", "Lymph Node Enlargement (% patients)", "Elevated LDH (% patients)")
clin.df$`MBC-like` <- mbc.values
clin.df$`PC-like` <- pc.values
clin.df$Variable <- c("Number of patients", "Age", "BM Involvement (%)","Spleen Enlargement (% patients)", "Lymph Node Enlargement (% patients)", "IgM (mg/dL)", "Hemoglobin (g/dL)", "Platelets (g/L)", "Elevated LDH (% patients)", "Overall Survival")
clin.df
```
# T-test for relevant variables
```{r}
# two-sided T-test for IgM
igm.t.test <- dat.core34 %>% 
  drop_na(IgM.New, SUBTYPE) %>%
  t_test(IgM.New ~ SUBTYPE, p.adjust.method = "bonferroni", alternative = "two.sided")
igm.pval <- round(as.numeric(igm.t.test$p), 3)

dat.core34 %>% 
  drop_na(DIAG.IgM, SUBTYPE) %>%
  t_test(DIAG.IgM ~ SUBTYPE, p.adjust.method = "bonferroni", alternative = "two.sided")

# two-sided T-test for infiltration
infilt.t.test <- dat.core34 %>% 
  drop_na(DIAG.INFILT, SUBTYPE) %>%
  t_test(DIAG.INFILT ~ SUBTYPE, p.adjust.method = "bonferroni", alternative = "two.sided")
infilt.pval <- round(as.numeric(infilt.t.test$p), 3)

# two-sided T-test for hemoglobin
hemo.t.test <- dat.core34 %>% 
  drop_na(DIAG.HB, SUBTYPE) %>%
  t_test(DIAG.HB ~ SUBTYPE, p.adjust.method = "bonferroni", alternative = "two.sided")
hemo.pval <- round(as.numeric(hemo.t.test$p), 3)

# two-sided T-test for platelets
plat.t.test <- dat.core34 %>% 
  drop_na(DIAG.PLAT, SUBTYPE) %>%
  t_test(DIAG.PLAT ~ SUBTYPE, p.adjust.method = "bonferroni", alternative = "two.sided")
plat.pval <- round(as.numeric(plat.t.test$p), 3)

# fisher-test for enlarged spleen
spleen.pval <- dat.core34 %>% 
  dplyr::select(DIAG.SPM, SUBTYPE) %>%
  drop_na(DIAG.SPM, SUBTYPE) %>%
  summarise(pval = fisher.test(SUBTYPE, DIAG.SPM)$p.value)
spleen.pval <- round(as.numeric(spleen.pval), 3)

# fisher-test for enlarged lymph nodes
lymph.pval <- dat.core34 %>% 
  dplyr::select(DIAG.ADNP, SUBTYPE) %>%
  drop_na(DIAG.ADNP, SUBTYPE) %>%
  summarise(fisher.test(SUBTYPE, DIAG.ADNP)$p.value)
lymph.pval <- round(as.numeric(lymph.pval), 3)

# fisher-test for elevated LDH
ldh.pval <- dat.core34 %>% 
  dplyr::select(DIAG.LDH, SUBTYPE) %>%
  drop_na(DIAG.LDH, SUBTYPE) %>%
  summarise(fisher.test(SUBTYPE, DIAG.LDH)$p.value)
ldh.pval <- round(as.numeric(ldh.pval), 3)

# two-sided T-test for OS
os.t.test <- dat.core34 %>% 
  drop_na(Time.OS, SUBTYPE) %>%
  t_test(Time.OS ~ SUBTYPE, p.adjust.method = "bonferroni", alternative = "two.sided")
os.pval <- round(as.numeric(os.t.test$p), 3)

# Checking statistics of sex
sex.pval <- dat.core34 %>% 
  dplyr::select(SEX, SUBTYPE) %>%
  drop_na(SEX, SUBTYPE) %>%
  summarise(fisher.test(SUBTYPE, SEX)$p.value)
round(as.numeric(sex.pval), 3)

# Checking statistics of age
age.ttest <- dat.core34 %>% 
  dplyr::select(AGE.DIAG, SUBTYPE) %>%
  t_test(AGE.DIAG ~ SUBTYPE, p.adjust.method = "bonferroni", alternative = "two.sided")
age.pval <- round(as.numeric(age.ttest$p), 3)

```
# Add p values to clinical df
```{r}
# Create vector of p-values for table
p.values <- c("", 
              "",
              infilt.pval,
              spleen.pval,
              lymph.pval,
              igm.pval,
              hemo.pval,
              plat.pval,
              ldh.pval,
              os.pval)

clin.df$`p-value` <- p.values

clin.df

# Sanity check on these 2...smaller difference has smaller p-value...would expect opposite. But visual confirmation is assuring
ggplot(dat, aes(x = SUBTYPE, y = IgM.New, fill = SUBTYPE)) + geom_boxplot()
ggplot(dat, aes(x = SUBTYPE, y = DIAG.HB, fill = SUBTYPE)) + geom_boxplot()

```
```{r}
# Spleen enlargement check
mbc.dat$DIAG.SPM # 3/8 = 36%
pcint.dat$DIAG.SPM # 1/18 = 5%

# Lymph enlargement check
mbc.dat$DIAG.ADNP # 2/8 = 25%
pcint.dat$DIAG.ADNP # 28%

# Elevate LDH check
mbc.dat$DIAG.LDH # 3/8 = 36%
pcint.dat$DIAG.LDH # 

```

# Good table
```{r}
library(flextable)
table_caption <- c("Clinical Characteristics at Diagnosis by Subtype", "Table 1")
head(df)

# Run it
df.table <- clin.df |>
  flextable() |>
  add_header_lines(values = rev(table_caption)) |>
  padding(padding = 0, part = "all") |>
  padding(padding.right = 10, part = "all") |>
  autofit() |>
  bold(part = "header", i = 1) |>
  colformat_int(i = "Number of patients") |>
  italic(part = "header", i = c(2:length(table_caption))) |>
  align(part = "header", i = c(1:length(table_caption)), align = "left") |>
  border(part = "head", i = c(1:length(table_caption)),
         border = list("width" = 0, color = "black", style = "solid"))
save_as_docx(df.table, path = "/Users/gagled01/morganLab/Waldenstroms/WM_Subtype_ClinicalCharacteristics_Table1.docx", align = "center")
```


# Trying statistical tests
```{r}
clin.df

# Try t-test
igm.ttest <- t.test(as.numeric(dat$DIAG.IgM) ~ as.character(dat$SUBTYPE), alternative = "two.sided")
infilt.ttest <- t.test(as.numeric(dat$DIAG.INFILT) ~ as.character(dat$SUBTYPE), alternative = "two.sided")
hemo.ttest <- t.test(as.numeric(dat$DIAG.HB) ~ as.character(dat$SUBTYPE), alternative = "two.sided")
plat.ttest <- t.test(as.numeric(dat$DIAG.PLAT) ~ as.character(dat$SUBTYPE), alternative = "two.sided")

chisq.test(dat$DIAG.SPM, dat$SUBTYPE)
chisq.test(dat$DIAG.ADNP, dat$SUBTYPE)
chisq.test(dat$DIAG.LDH, dat$SUBTYPE)

igm.ttest$p.value
infilt.ttest$p.value
hemo.ttest$p.value
plat.ttest$p.value



clin.df$p.value

```

