---
title: "Untitled"
output: html_document
date: "2024-04-23"
---

```{r}
library(Seurat)
library(ggplot2)
options(future.globals.maxSize=10000000000000000000000000) 
```
# Load data, filter only WM samples, recluster
```{r}
scrna <- readRDS("/Users/gagled01/morganLab/Waldenstroms/singlecell/objects/scRNA_SCTransformIntegrated_CTAnnotated_ReferenceAdd_Filtered_NoRegress.rds")
#scnra.sub <- scrna
Idents(scrna) <- "patient"

scrna.subby <- subset(scrna, idents = c("01-076", "01-115", "01-131", "01-163", "01-190", "04-003", "04-006",
                                            "WM25", "WM43", "WM47", "WM54", "WM65", "tonsil1", "tonsil2", "tonsil3"))

#random.subsample <- sample(colnames(scrna.subby), 100000, replace = F)

# Reclustering based on integrated assay (which is effectively batch corrected)
DefaultAssay(scrna.subby) <- "integrated"
scrna.subby <- ScaleData(scrna.subby)
scrna.subby <- RunPCA(scrna.subby, npcs = 20)
scrna.subby <- FindNeighbors(scrna.subby, dims = 1:20)
scrna.subby <- FindClusters(scrna.subby, resolution = 0.5)
scrna.subby <- RunUMAP(scrna.subby, dims = 1:20)

DefaultAssay(scrna.subby) <- "RNA"
scrna.subby <- NormalizeData(scrna.subby, normalization.method = "LogNormalize", scale.factor = 10000)
#scrna.subby <- ScaleData(scrna.subby)

saveRDS(scrna.subby, "/Users/gagled01/morganLab/Waldenstroms/singlecell/objects/SeuratAnalysis_ReclusteredObject_12.3.2024.rds")
```
# Supp figure 1
```{r}
genes <- c("MS4A1", "CD74", "HLA-DRA",
           "JCHAIN", "MZB1", "XBP1",
           "MME", "MKI67", "VPREB1",
           "IGLL1", "CD24", "CD79B")

# Feature Plots
FeaturePlot(scrna.subby, features = genes) & theme(axis.text.x = element_blank(),
                                                   axis.text.y = element_blank(),
                                                   axis.title.x = element_blank(),
                                                   axis.title.y = element_blank())
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Supplementary/SuppFig1_scRNA_MarkerGene_FeaturePlots.pdf", height = 9, width = 12)

# Violin Plots
VlnPlot(scrna.subby, features = genes, group.by = "majority_voting", pt.size = 0) & theme(axis.text.x = element_blank(),
                                                                             axis.title.x = element_blank())
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Supplementary/SuppFig1_scRNA_MarkerGene_ViolinPlots.pdf", height = 9, width = 12)

DimPlot(scrna.subby, raster = F, group.by = "majority_voting") + ggtitle("") + theme(axis.text.x = element_blank(),
                                                                       axis.text.y = element_blank(),
                                                                       axis.title.x = element_blank(),
                                                                       axis.title.y = element_blank(),
                                                                       axis.ticks.y = element_blank(),
                                                                       axis.ticks.x = element_blank()) + NoLegend()
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Supplementary/scRNA_PatientsRef_UMAP_CellTypes.png", height = 6, width = 6)
DimPlot(scrna.subby, raster = F, group.by = "patient") + ggtitle("") + theme(axis.text.x = element_blank(),
                                                                       axis.text.y = element_blank(),
                                                                       axis.title.x = element_blank(),
                                                                       axis.title.y = element_blank(),
                                                                       axis.ticks.y = element_blank(),
                                                                       axis.ticks.x = element_blank()) + NoLegend()
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Supplementary/scRNA_PatientsRef_UMAP_Patients.png", height = 6, width = 6)

DimPlot(scrna.subby, raster = F, group.by = "majority_voting") 
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Supplementary/scRNA_PatientsRef_UMAP_CellTypes_withLegend.png", height = 6, width = 6)
DimPlot(scrna.subby, raster = F, group.by = "patient")
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Supplementary/scRNA_PatientsRef_UMAP_Patients_withLegend.png", height = 6, width = 6)
```
# Supp figure 3/4
```{r}
genes <- c("IGHM", "IGHG1", "IGHD", "IGHA1", "CD27", "FCRL4", "FCRL5", "RUNX2",
           "ITGAX", "SOX5", "DLL1", "AICDA", "CR2", "CXCR5")

# Feature Plots
FeaturePlot(scrna.subby, features = genes) & theme(axis.text.x = element_blank(),
                                                   axis.text.y = element_blank(),
                                                   axis.title.x = element_blank(),
                                                   axis.title.y = element_blank())
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Supplementary/SuppFig3_scRNA_Seurat_FeaturePlots.pdf", height = 9, width = 12)

# Violin Plots
VlnPlot(scrna.subby, features = genes, group.by = "majority_voting", pt.size = 0) & theme(
                                                                             axis.title.x = element_blank())
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Supplementary/SuppFig3_scRNA_ViolinPlots.pdf", height = 9, width = 12)

# Heatmap scaled
DefaultAssay(scrna.subby) <- "SCT"
DoHeatmap(scrna.subby, features = genes, group.by = "majority_voting") # Scaled
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Supplementary/SuppFigure1/scRNA_MBC_SurfaceMarkers_Heatmap_Scaled.png", height = 8, width = 6)

# Heatmap unscaled
DoHeatmap(scrna.subby, features = genes, group.by = "patient", slot = "data") # Unscaled
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Supplementary/SuppFigure1/scRNA_MBC_SurfaceMarkers_Heatmap_Unscaled.pdf", height = 8, width = 6)
```


# Subbing out MBC only
```{r}
scrna.subby <- readRDS("/Users/gagled01/morganLab/Waldenstroms/singlecell/objects/scRNA_SCTransformIntegrated_CTAnnotated_ReferenceAdd_Filtered_NoRegress.rds")
Idents(scrna.subby) <- "majority_voting"
scrna.subby2 <- subset(scrna.subby, idents = c("Memory B cells"))

DefaultAssay(scrna.subby2) <- "integrated"
scrna.subby2 <- ScaleData(scrna.subby2)
scrna.subby2 <- RunPCA(scrna.subby2, npcs = 20)
scrna.subby2 <- FindNeighbors(scrna.subby2, dims = 1:20)
scrna.subby2 <- FindClusters(scrna.subby2, resolution = 0.5)
scrna.subby2 <- RunUMAP(scrna.subby2, dims = 1:20)


genes <- c("IGHM", "IGHG1", "IGHD", "IGHA1", "CD27", "FCRL4", "FCRL5", "RUNX2",
           "ITGAX", "SOX5", "CR2", "CXCR5")

DefaultAssay(scrna.subby2) <- "RNA"
scrna.subby2 <- NormalizeData(scrna.subby2, normalization.method = "LogNormalize", scale.factor = 10000)
scrna.subby2 <- ScaleData(scrna.subby2)


DimPlot(scrna.subby2, group.by = "majority_voting")
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/SuppFigure3/scRNA_SCTransformInt_CTAnnotationUMAP_Filtered_PatientsOnly_Reclustered_NoRegress_REFMBCNONAIVE-ONLY_Celltype_Integrated-Assay.pdf", height = 6, width = 8)
DimPlot(scrna.subby2, group.by = "patient")
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/SuppFigure3/scRNA_SCTransformInt_CTAnnotationUMAP_Filtered_PatientsOnly_Reclustered_NoRegress_REFMBCNONAIVE-ONLY_Integrated-Assay.pdf", height = 6, width = 8)

# Feature Plots
FeaturePlot(scrna.subby2, features = genes)
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/SuppFigure3/scRNA_Filtered_PatientsOnly_Reclustered_NoRegress_REFMBCNONAIVE-ONLY_MBCsubSetGenes_FeaturePlots.pdf", height = 9, width = 12)

# Violin Plots
VlnPlot(scrna.subby2, features = genes, group.by = "majority_voting") & theme(axis.text.x = element_blank(),
                                                                             axis.title.x = element_blank())
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/SuppFigure3/scRNA_Filtered_PatientsOnly_Reclustered_NoRegress_REFMBC-ONLY_MBCsubSetGenes_ViolinPlots.pdf", height = 9, width = 12)
```

```{r}
scrna <- readRDS("/Users/gagled01/morganLab/Waldenstroms/singlecell/objects/scRNA_SCTransformIntegrated_CTAnnotated_ReferenceAdd_Filtered_NoRegress.rds")
#scnra.sub <- scrna
Idents(scrna) <- "patient"

scrna.subby <- subset(scrna, idents = c("tonsil1", "tonsil2", "tonsil3"))

Idents(scrna.subby) <- "majority_voting"
scrna.double.sub <- subset(scrna.subby, idents = "Memory B cells")

DefaultAssay(scrna.double.sub) <- "integrated"
scrna.double.sub <- ScaleData(scrna.double.sub)
scrna.double.sub <- RunPCA(scrna.double.sub, npcs = 20)
scrna.double.sub <- FindNeighbors(scrna.double.sub, dims = 1:20)
scrna.double.sub <- FindClusters(scrna.double.sub, resolution = 0.5)
scrna.double.sub <- RunUMAP(scrna.double.sub, dims = 1:20)

DefaultAssay(scrna.double.sub) <- "RNA"
scrna.double.sub <- NormalizeData(scrna.double.sub, normalization.method = "LogNormalize", scale.factor = 10000)
scrna.double.sub <- ScaleData(scrna.double.sub)

genes <- c("IGHM", "IGHG1", "IGHD", "IGHA1", "CD27", "FCRL4", "FCRL5", "RUNX2",
           "ITGAX", "SOX5", "DLL1", "AICDA", "CR2", "CXCR5")

DimPlot(scrna.double.sub, group.by = "majority_voting")
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_ReferenceMBCsOnly_CellTypeUMAP.png", height = 6, width = 8)
DimPlot(scrna.double.sub, group.by = "patient")
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_ReferenceMBCsOnly_PatientUMAP.png", height = 6, width = 8)

# Feature Plots
FeaturePlot(scrna.double.sub, features = genes)
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_ReferenceMBCsOnly_MBCsubSetGenes_FeaturePlots.png", height = 9, width = 12)

# Violin Plots
VlnPlot(scrna.double.sub, features = genes, group.by = "majority_voting") & theme(axis.text.x = element_blank(),
                                                                             axis.title.x = element_blank())
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_ReferenceMBCsOnly_MBCsubSetGenes_ViolinPlots.png", height = 9, width = 12)

# Heatmap scaled
DoHeatmap(scrna.double.sub, features = c("IGHM", "IGHG1", "IGHD", "IGHA1", "CD27", "FCRL4", "FCRL5", "RUNX2", 
                                  "ITGAX", "SOX5", "DLL1", "AICDA", "CR2", "CXCR5"), group.by = "majority_voting") # Scaled
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_ReferenceMBCsOnly_Heatmap_MBCsubSetGenes_Scaled.png", height = 8, width = 6)
```
# Barplots of relative abundance from scRNA celltypist UNCORRECTED
# Dirty way to get celltype relative abundance by patient dataframe for stacked barplots

# Stacked bar plot of cell type relative abundances
```{r}
############### WM SAMPLES
p01.076.ids <- BiocGenerics::which(scrna.subby@meta.data$patient %in% "01-076")
p01.076.celltypes <- scrna.subby@meta.data$majority_voting[p01.076.ids]
p01.115.ids <- BiocGenerics::which(scrna.subby@meta.data$patient %in% "01-115")
p01.115.celltypes <- scrna.subby@meta.data$majority_voting[p01.115.ids]
p01.131.ids <- BiocGenerics::which(scrna.subby@meta.data$patient %in% "01-131")
p01.131.celltypes <- scrna.subby@meta.data$majority_voting[p01.131.ids]
p01.163.ids <- BiocGenerics::which(scrna.subby@meta.data$patient %in% "01-163")
p01.163.celltypes <- scrna.subby@meta.data$majority_voting[p01.163.ids]
p01.190.ids <- BiocGenerics::which(scrna.subby@meta.data$patient %in% "01-190")
p01.190.celltypes <- scrna.subby@meta.data$majority_voting[p01.190.ids]
p04.003.ids <- BiocGenerics::which(scrna.subby@meta.data$patient %in% "04-003")
p04.003.celltypes <- scrna.subby@meta.data$majority_voting[p04.003.ids]
p04.006.ids <- BiocGenerics::which(scrna.subby@meta.data$patient %in% "04-006")
p04.006.celltypes <- scrna.subby@meta.data$majority_voting[p04.006.ids]
wm25.ids <- BiocGenerics::which(scrna.subby@meta.data$patient %in% "WM25")
wm25.celltypes <- scrna.subby@meta.data$majority_voting[wm25.ids]
wm43.ids <- BiocGenerics::which(scrna.subby@meta.data$patient %in% "WM43")
wm43.celltypes <- scrna.subby@meta.data$majority_voting[wm43.ids]
wm47.ids <- BiocGenerics::which(scrna.subby@meta.data$patient %in% "WM47")
wm47.celltypes <- scrna.subby@meta.data$majority_voting[wm47.ids]
wm54.ids <- BiocGenerics::which(scrna.subby@meta.data$patient %in% "WM54")
wm54.celltypes <- scrna.subby@meta.data$majority_voting[wm54.ids]
wm65.ids <- BiocGenerics::which(scrna.subby@meta.data$patient %in% "WM65")
wm65.celltypes <- scrna.subby@meta.data$majority_voting[wm65.ids]
tonsil1.ids <- BiocGenerics::which(scrna.subby@meta.data$patient %in% "tonsil1")
tonsil1.celltypes <- scrna.subby@meta.data$majority_voting[tonsil1.ids]
tonsil2.ids <- BiocGenerics::which(scrna.subby@meta.data$patient %in% "tonsil2")
tonsil2.celltypes <- scrna.subby@meta.data$majority_voting[tonsil2.ids]
tonsil3.ids <- BiocGenerics::which(scrna.subby@meta.data$patient %in% "tonsil3")
tonsil3.celltypes <- scrna.subby@meta.data$majority_voting[tonsil3.ids]

library(tidyverse)

# Relative abundance by patient...requires a lot of fennegling bcuz different patients have different cell populations
p01.076_relabun <- data.frame(table(p01.076.celltypes)/sum(table(p01.076.celltypes)) * 100)
p01.076_relabun$Patient <- "01-076"
colnames(p01.076_relabun)[1] <- "Celltype"
#missing.celltypes <- setdiff(table(names(scrna.subby@meta.data$majority_voting)), table(names(p01.076_relabun$Celltype)))
#missing.df <- data.frame(matrix(NA, nrow = length(missing.celltypes), ncol = 3))
#colnames(missing.df) <- c("Celltype", "Freq", "Patient")
#missing.df$Celltype <- missing.celltypes
#missing.df$Patient <- "01-076"
#p01.076.mergedf <- rbind(p01.076_relabun, missing.df)
p01.076.mergedf <- p01.076_relabun

p01.115_relabun <- data.frame(table(p01.115.celltypes)/sum(table(p01.115.celltypes)) * 100)
p01.115_relabun$Patient <- "01-115"
colnames(p01.115_relabun)[1] <- "Celltype"
# missing.celltypes <- setdiff(subpoo.archR$annotation2, p01.115_relabun$Celltype)
# missing.df <- data.frame(matrix(NA, nrow = length(missing.celltypes), ncol = 3))
# colnames(missing.df) <- c("Celltype", "Freq", "Patient")
# missing.df$Celltype <- missing.celltypes
# missing.df$Patient <- "01-115"
# p01.115.mergedf <- rbind(p01.115_relabun, missing.df)
p01.115.mergedf <- p01.115_relabun # because it has all celltypes!

p01.131_relabun <- data.frame(table(p01.131.celltypes)/sum(table(p01.131.celltypes)) * 100)
p01.131_relabun$Patient <- "01-131"
colnames(p01.131_relabun)[1] <- "Celltype"
#missing.celltypes <- setdiff(scrna.subby@meta.data$majority_voting, p01.131_relabun$Celltype)
#missing.df <- data.frame(matrix(NA, nrow = length(missing.celltypes), ncol = 3))
#colnames(missing.df) <- c("Celltype", "Freq", "Patient")
#missing.df$Celltype <- missing.celltypes
#missing.df$Patient <- "01-131"
#p01.131.mergedf <- rbind(p01.131_relabun, missing.df)
p01.131.mergedf <- p01.131_relabun

p01.163_relabun <- data.frame(table(p01.163.celltypes)/sum(table(p01.163.celltypes)) * 100)
p01.163_relabun$Patient <- "01-163"
colnames(p01.163_relabun)[1] <- "Celltype"
#missing.celltypes <- setdiff(scrna.subby@meta.data$majority_voting, p01.163_relabun$Celltype)
#missing.df <- data.frame(matrix(NA, nrow = length(missing.celltypes), ncol = 3))
#colnames(missing.df) <- c("Celltype", "Freq", "Patient")
#missing.df$Celltype <- missing.celltypes
#missing.df$Patient <- "01-163"
#p01.163.mergedf <- rbind(p01.163_relabun, missing.df)
p01.163.mergedf <- p01.163_relabun

p01.190_relabun <- data.frame(table(p01.190.celltypes)/sum(table(p01.190.celltypes)) * 100)
p01.190_relabun$Patient <- "01-190"
colnames(p01.190_relabun)[1] <- "Celltype"
#missing.celltypes <- setdiff(scrna.subby@meta.data$majority_voting, p01.190_relabun$Celltype)
#missing.df <- data.frame(matrix(NA, nrow = length(missing.celltypes), ncol = 3))
#colnames(missing.df) <- c("Celltype", "Freq", "Patient")
#missing.df$Celltype <- missing.celltypes
#missing.df$Patient <- "01-190"
#p01.190.mergedf <- rbind(p01.190_relabun, missing.df)
p01.190.mergedf <- p01.190_relabun

p04.003_relabun <- data.frame(table(p04.003.celltypes)/sum(table(p04.003.celltypes)) * 100)
p04.003_relabun$Patient <- "04-003"
colnames(p04.003_relabun)[1] <- "Celltype"
# missing.celltypes <- setdiff(subpoo.archR$annotation2, p04.003_relabun$Celltype)
# missing.df <- data.frame(matrix(NA, nrow = length(missing.celltypes), ncol = 3))
# colnames(missing.df) <- c("Celltype", "Freq", "Patient")
# missing.df$Celltype <- missing.celltypes
# missing.df$Patient <- "04-003"
# p04.003.mergedf <- rbind(p04.003_relabun, missing.df)
p04.003.mergedf <- p04.003_relabun # because it has all celltypes!

p04.006_relabun <- data.frame(table(p04.006.celltypes)/sum(table(p04.006.celltypes)) * 100)
p04.006_relabun$Patient <- "04-006"
colnames(p04.006_relabun)[1] <- "Celltype"
#missing.celltypes <- setdiff(scrna.subby@meta.data$majority_voting, p04.006_relabun$Celltype)
#missing.df <- data.frame(matrix(NA, nrow = length(missing.celltypes), ncol = 3))
#colnames(missing.df) <- c("Celltype", "Freq", "Patient")
#missing.df$Celltype <- missing.celltypes
#missing.df$Patient <- "04-006"
#p04.006.mergedf <- rbind(p04.006_relabun, missing.df)
p04.006.mergedf <- p04.006_relabun

###################################### GOUSTAV ROUSSY SAMPLES

wm25_relabun <- data.frame(table(wm25.celltypes)/sum(table(wm25.celltypes)) * 100)
wm25_relabun$Patient <- "WM25"
colnames(wm25_relabun)[1] <- "Celltype"
#missing.celltypes <- setdiff(scrna.subby@meta.data$majority_voting, wm25_relabun$Celltype)
#missing.df <- data.frame(matrix(NA, nrow = length(missing.celltypes), ncol = 3))
#colnames(missing.df) <- c("Celltype", "Freq", "Patient")
#missing.df$Celltype <- missing.celltypes
#missing.df$Patient <- "WM25"
#wm25.mergedf <- rbind(wm25_relabun, missing.df)
wm25.mergedf <- wm25_relabun

wm43_relabun <- data.frame(table(wm43.celltypes)/sum(table(wm43.celltypes)) * 100)
wm43_relabun$Patient <- "WM43"
colnames(wm43_relabun)[1] <- "Celltype"
# missing.celltypes <- setdiff(subpoo.archR$annotation2, wm43_relabun$Celltype)
# missing.df <- data.frame(matrix(NA, nrow = length(missing.celltypes), ncol = 3))
# colnames(missing.df) <- c("Celltype", "Freq", "Patient")
# missing.df$Celltype <- missing.celltypes
# missing.df$Patient <- "Wm43"
# wm43.mergedf <- rbind(wm43_relabun, missing.df)
wm43.mergedf <- wm43_relabun # because it has all celltypes

wm47_relabun <- data.frame(table(wm47.celltypes)/sum(table(wm47.celltypes)) * 100)
wm47_relabun$Patient <- "WM47"
colnames(wm47_relabun)[1] <- "Celltype"
# missing.celltypes <- setdiff(subpoo.archR$annotation2, wm47_relabun$Celltype)
# missing.df <- data.frame(matrix(NA, nrow = length(missing.celltypes), ncol = 3))
# colnames(missing.df) <- c("Celltype", "Freq", "Patient")
# missing.df$Celltype <- missing.celltypes
# missing.df$Patient <- "WM47"
# wm47.mergedf <- rbind(wm47_relabun, missing.df)
wm47.mergedf <- wm47_relabun # because it has all celltypes

wm54_relabun <- data.frame(table(wm54.celltypes)/sum(table(wm54.celltypes)) * 100)
wm54_relabun$Patient <- "WM54"
colnames(wm54_relabun)[1] <- "Celltype"
# missing.celltypes <- setdiff(subpoo.archR$annotation2, wm54_relabun$Celltype)
# missing.df <- data.frame(matrix(NA, nrow = length(missing.celltypes), ncol = 3))
# colnames(missing.df) <- c("Celltype", "Freq", "Patient")
# missing.df$Celltype <- missing.celltypes
# missing.df$Patient <- "WM54"
# wm54.mergedf <- rbind(wm54_relabun, missing.df)
wm54.mergedf <- wm54_relabun # because it has all celltypes

wm65_relabun <- data.frame(table(wm65.celltypes)/sum(table(wm65.celltypes)) * 100)
wm65_relabun$Patient <- "WM65"
colnames(wm65_relabun)[1] <- "Celltype"
#missing.celltypes <- setdiff(scrna.subby@meta.data$majority_voting, wm65_relabun$Celltype)
#missing.df <- data.frame(matrix(NA, nrow = length(missing.celltypes), ncol = 3))
#colnames(missing.df) <- c("Celltype", "Freq", "Patient")
#missing.df$Celltype <- missing.celltypes
#missing.df$Patient <- "WM65"
#wm65.mergedf <- rbind(wm65_relabun, missing.df)
wm65.mergedf <- wm65_relabun

tonsil1_relabun <- data.frame(table(tonsil1.celltypes)/sum(table(tonsil1.celltypes)) * 100)
tonsil1_relabun$Patient <- "tonsil1"
colnames(tonsil1_relabun)[1] <- "Celltype"
#missing.celltypes <- setdiff(scrna.subby@meta.data$majority_voting, tonsil1_relabun$Celltype)
#missing.df <- data.frame(matrix(NA, nrow = length(missing.celltypes), ncol = 3))
#colnames(missing.df) <- c("Celltype", "Freq", "Patient")
#missing.df$Celltype <- missing.celltypes
#missing.df$Patient <- "tonsil1"
#tonsil1.mergedf <- rbind(tonsil1_relabun, missing.df)
tonsil1.mergdf <- tonsil1_relabun

tonsil2_relabun <- data.frame(table(tonsil2.celltypes)/sum(table(tonsil2.celltypes)) * 100)
tonsil2_relabun$Patient <- "tonsil2"
colnames(tonsil2_relabun)[1] <- "Celltype"
#missing.celltypes <- setdiff(scrna.subby@meta.data$majority_voting, tonsil2_relabun$Celltype)
#missing.df <- data.frame(matrix(NA, nrow = length(missing.celltypes), ncol = 3))
#colnames(missing.df) <- c("Celltype", "Freq", "Patient")
#missing.df$Celltype <- missing.celltypes
#missing.df$Patient <- "tonsil2"
#tonsil2.mergedf <- rbind(tonsil2_relabun, missing.df)
tonsil2.mergdf <- tonsil2_relabun

tonsil3_relabun <- data.frame(table(tonsil3.celltypes)/sum(table(tonsil3.celltypes)) * 100)
tonsil3_relabun$Patient <- "tonsil3"
colnames(tonsil3_relabun)[1] <- "Celltype"
#missing.celltypes <- setdiff(scrna.subby@meta.data$majority_voting, tonsil3_relabun$Celltype)
#missing.df <- data.frame(matrix(NA, nrow = length(missing.celltypes), ncol = 3))
#colnames(missing.df) <- c("Celltype", "Freq", "Patient")
#missing.df$Celltype <- missing.celltypes
#missing.df$Patient <- "tonsil3"
#tonsil3.mergedf <- rbind(tonsil3_relabun, missing.df)
tonsil3.mergdf <- tonsil3_relabun

allpatient_df <- rbind(p01.076.mergedf, p01.115.mergedf, p01.131.mergedf, p01.163.mergedf, p01.190.mergedf, p04.003.mergedf, p04.006.mergedf, 
                       wm25.mergedf, wm43.mergedf, wm47.mergedf, wm54.mergedf, wm65.mergedf, tonsil1.mergdf, tonsil2.mergdf, tonsil3.mergdf)

# factor so plasma cells come up first
#allpatient_df$Celltype <- factor(allpatient_df$Celltype, levels = c("Clonal MBC", "Clonal PCs", "Non-clonal MBC", "Reference MBC", "Reference PC"))

# similar w patients
#allpatient_df$Patient <- factor(allpatient_df$Patient, levels = c( "BCP003", "BCP004", "BCP005", "BCP006",
#                                                                  "stanford1", "stanford2", "stanford3", "01-076", "01-115", "01-131", "01-163", "01-190", "04-003", "04-006",
#                                                                  "WM25", "WM43", "WM46", "WM47", "WM54", "WM65"
#                                                                 ))
#allpatient_df$Patient <- droplevels(allpatient_df$Patient)

# Stacked barplot
ggplot(allpatient_df, aes(fill=Celltype, y=Freq, x=Patient)) + 
    geom_bar(position="stack", stat="identity", width = 0.5) + 
  xlab(label = "Patient") + ylab("Relative Abundance") + theme_minimal() + 
  guides(fill = guide_legend(nrow = 1)) +
  theme(axis.text.y = element_text(size = "10", vjust = 0.5, hjust = 0.5, face = "bold"),
        axis.text.x = element_text(size = "10", vjust = 0.5, hjust = 0.5, face = "bold"),
        axis.title.x = element_text(size = "15", face = "bold"),
        axis.title.y = element_text(size = "15", face = "bold"),
        legend.position = "top") 
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Supplementary/WM_SupplementaryFigure1_scRNA_CellTypist_Barplot.pdf", width = 10, height = 5)
```

```{r}
genes <- c("MS4A1", "CD74", "HLA-DRA", "JCHAIN", "MZB1", "XBP1")

# Feature Plots
p <- FeaturePlot(scrna.subby, features = genes, combine = FALSE)
for(i in 1:length(p)) {
  p[[i]] <- p[[i]] + NoLegend() + theme(axis.title.x = element_blank())
}
cowplot::plot_grid(plotlist = p)
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_CellTypist_MarkerAnnotation_FeaturePlots.png", height = 9, width = 12)

# Violin Plots
p <- VlnPlot(scrna.subby, features = genes, group.by = "majority_voting", combine = FALSE)
for(i in 1:length(p)) {
  p[[i]] <- p[[i]] + NoLegend() + theme(axis.title.x = element_blank(),
                                        axis.text.x = element_blank())
}
cowplot::plot_grid(plotlist = p)
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_CellTypist_MarkerAnnotation_ViolinPlots.png", height = 9, width = 9)

# Heatmap scaled
#DoHeatmap(scrna.subby, features = c("IGHM", "IGHG1", "IGHD", "IGHA1", "CD27", "FCRL4", "FCRL5", "RUNX2", 
#                                  "ITGAX", "SOX5", "DLL1", "AICDA", "CR2", "CXCR5"), group.by = "patient") # Scaled
#ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/fleebo.png", height = 8, width = 6)
```

