---
title: "Untitled"
output: html_document
date: "2023-07-18"
---
```{r}
library(DOSE)
library(enrichplot)
library(ggplot2)
```
# Load GSEA outputs
```{r}
mbc.like_vs_pc.like_gsea <- read.table("/Users/gagled01/morganLab/Waldenstroms/singlecell/MBClike_vs_PClike_RankedList_upMBC.tsv", sep = "\t", header = T)
pc.like_vs_mbc.like_gsea <- read.table("/Users/gagled01/morganLab/Waldenstroms/singlecell/MBClike_vs_PClike_RankedList_upPC.tsv", sep = "\t", header = T)
```
# Create dataframes for plotting
```{r}
plotting.df <- data.frame(mbc.like_vs_pc.like_gsea$NAME, mbc.like_vs_pc.like_gsea$NES, mbc.like_vs_pc.like_gsea$FDR.q.val, mbc.like_vs_pc.like_gsea$SIZE)
plotting.df <- head(plotting.df, n = 25)
colnames(plotting.df) <- c("Pathway", "NES", "FDR.q.val", "Count")
plotting.df$Pathway <- gsub("HALLMARK_", "", plotting.df$Pathway)
plotting.df$Pathway <- c("Allograft Rejection", "Apical Junction", "G2M Checkpoint", "E2F Targets", "Mitotic Spindle", "Interferon Gamma Response", "IL2/STAT5 Signaling", 
                         "Myogenesis", "PI3K/AKT/MTOR Signaling", "MYC Targets v1", "Complement", "MTORC1 Signaling", "p53 Pathway", "KRAS Signaling", "Apoptosis", "DNA Repair", "Oxidative Phosphorylation",
                         "Peroxisome", "UV Response Down", "Interferon Alpha Response", "Cholesterol Homeostasis", "Estrogen Response Late", "Androgen Response", "Bile Acid Metabolism", "Coagulation" 
                         )
plotting.df$log10FDR.qval <- -log10(plotting.df$FDR.q.val)

plotting.df2 <- data.frame(pc.like_vs_mbc.like_gsea$NAME, pc.like_vs_mbc.like_gsea$NES, pc.like_vs_mbc.like_gsea$FDR.q.val, pc.like_vs_mbc.like_gsea$SIZE)
plotting.df2 <- head(plotting.df2, n = 25)
colnames(plotting.df2) <- c("Pathway", "NES", "FDR.q.val", "Count")
#plotting.df2$FDR.q.val[1:2] <- 0.0001 # Manually giving some v low Q values because 0 does not work for plotting
plotting.df2$Pathway <- gsub("HALLMARK_", "", plotting.df2$Pathway)
plotting.df2$Pathway <- c("Heme Metabolism", "Estrogen Response Early", "Estrogen Response Late", "Apoptosis", "Androgen Response", "MTORC1 Signaling", "Inflammatory Response",
                         "IL2/STAT5 Signaling", "Adipogenesis", "TNFa Signaling via NF-kB", "KRAS Signaling", "Complement", "Xenobiotic Metabolism", "Interferon Gamma Response",
                         "Glycolysis", "Hypoxia", "Myogenesis", "UV Response Down", "UV Response UP", "p53 Pathway", "Epithelial-Mesenchymal Transition", "Apical Junction")
plotting.df2$log10FDR.qval <- -log10(plotting.df2$FDR.q.val)

```
# Subset out some of the less relevant pathways
```{r}
plotting.df <- plotting.df[plotting.df$Pathway %ni% c("Allograft Rejection", "Complement", "UV Response Down", "Peroxisome", "Bile Acid Metabolism", "Spermatogenesis", "Cholesterol Metabolism", "Coagulation", "Cholesterol Homeostasis", "Oxidative Phosphorylation", "Androgen Response", "Estrogen Response Late", "DNA Repair", "Interferon Alpha Response"),]
plotting.df2 <- plotting.df2[plotting.df2$Pathway %ni% c("Complement", "UV Response Down", "UV Response UP", "Apical Junction", "Epithelial-Mesenchymal Transition", "p53 Pathway", "Glycolysis", "Androgen Response", "Myogenesis", "Xenobiotic Metabolism", "Interferon Gamma Response", "Hypoxia", "KRAS Signaling", "Adipogenesis"),]
```
# Dot plot GSEA 
```{r}
# -log10FDR
#ggplot(plotting.df, aes(x=NES, y=reorder(Pathway,log10FDR.qval), fill=log10FDR.qval, size = Size)) + geom_point(aes(size=Count, color = log10FDR.qval)) + scale_color_gradient(low = "red", high = "blue", name = "-log10(FDR q-value)") +
#  ylab("") + theme_bw() + theme(legend.position = "right") 
#ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Figure3/MBC-like_vs_PC-like_GSEA_Dotplot_upMBC.pdf", height = 8, width = 8)

#ggplot(plotting.df2, aes(x=NES, y=reorder(Pathway,log10FDR.qval), fill=log10FDR.qval, size = Size)) + geom_point(aes(size=Count, color = log10FDR.qval)) + scale_color_gradient(low = "red", high = "blue", name = "-log10(FDR q-value)") +
#  ylab("") + theme_bw() + theme(legend.position = "right") 
#ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Figure3/PC-like_vs_MBC-like_GSEA_Dotplot_upPC.pdf", height = 8, width = 8)


# regular FDR
ggplot(plotting.df, aes(x=NES, y=reorder(Pathway,-FDR.q.val), size = Size)) + geom_point(aes(size=Count, color = FDR.q.val)) + scale_color_gradient(low = "blue", high = "red", name = "FDR q-value") +
  ylab("") + ggtitle("MBC-like MBC Enriched Pathways") + theme_bw() + theme(legend.position = "bottom",
                                                                            legend.text = element_text(size = 10),
                                                                            legend.title = element_text(size = 12, face = "bold")) + 
                                                                             theme(axis.text.y = element_text(size = 15, face = "bold"),
                                                                                   plot.title = element_text(hjust = 0.5, size = 18, face = "bold"))
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Figure3/MBC-like_vs_PC-like_GSEA_Dotplot_upMBC_FDRqval.pdf", height = 9, width = 8)

ggplot(plotting.df2, aes(x=NES, y=reorder(Pathway,-FDR.q.val),size = Size)) + geom_point(aes(size=Count, color = FDR.q.val)) + scale_color_gradient(low = "blue", high = "red", name = "FDR q-value") +
  ylab("") + ggtitle("PC-like MBC Enriched Pathways") + theme_bw() + theme(legend.position = "bottom",
                                                                           legend.text = element_text(size = 10),
                                                                           legend.title = element_text(size = 12, face = "bold"),
                                              axis.text.y = element_text(size = 15, face = "bold"),
                                              plot.title = element_text(hjust = 0.5, size = 18, face = "bold")) 
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Figure3/PC-like_vs_MBC-like_GSEA_Dotplot_upPC_FDRqval.pdf", height = 9, width = 8)
```
# Other styles of GSEA plot
```{r}

# using -log10(FDR)
ggplot(plotting.df, aes(x=NES, y=reorder(Pathway,log10FDR.qval), fill=log10FDR.qval)) + geom_bar(stat="identity")+scale_fill_gradient(low="red", high="blue", name = "-log10(FDR q-value)") +
  ylab("") + theme_bw() + theme(legend.position = "bottom") + guides(color=guide_legend("-log10(FDR q-value)"))
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/MBC-like_vs_PC-like_MBC_GSEA_Barplot.png", height = 8, width = 8)

ggplot(plotting.df2, aes(x=NES, y=reorder(Pathway,log10FDR.qval), fill=log10FDR.qval)) + geom_bar(stat="identity")+scale_fill_gradient(low="red", high="blue", name = "-log10(FDR q-value)") +
  ylab("") + theme_bw() + theme(legend.position = "bottom") + guides(color=guide_legend("-log10(FDR q-value)"))
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/PC-like_vs_MBC-like_MBC_GSEA_Barplot.png", height = 8, width = 8)

# using regular FDR cuz more interpretable
ggplot(plotting.df, aes(x=NES, y=reorder(Pathway,-FDR.q.val), fill=FDR.q.val)) + geom_bar(stat="identity")+scale_fill_gradient(low="blue", high="red", name = "FDR q-value") +
  ylab("") + theme_bw() + theme(legend.position = "bottom") + guides(color=guide_legend("FDR q-value"))
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/MBC-like_vs_PC-like_MBC_GSEA_Barplot_FDRqval.png", height = 8, width = 8)

ggplot(plotting.df2, aes(x=NES, y=reorder(Pathway,-FDR.q.val), fill=FDR.q.val)) + geom_bar(stat="identity")+scale_fill_gradient(low="blue", high="red", name = "FDR q-value") +
  ylab("") + theme_bw() + theme(legend.position = "bottom") + guides(color=guide_legend("FDR q-value"))
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/PC-like_vs_MBC-like_MBC_GSEA_Barplot_FDRqval.png", height = 8, width = 8)#
```
# rotate 90 degrees
```{r}
ggplot(plotting.df, aes(y=NES, x=reorder(Pathway,-log10FDR.qval), fill=log10FDR.qval)) + geom_bar(stat="identity")+scale_fill_gradient(low="red", high="blue", name = "-log10(FDR q-value)") +
  ylab("NES") + theme_minimal(base_size = 15) + theme(legend.position = "right",
                                     axis.text.x = element_text(angle = 90, hjust = 0.95, face = "bold")) + guides(color=guide_legend("-log10(FDR q-value)"))
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/PC-like-MBC_vs_MBC-like-MBC_GSEA_Barplot_Rotated.png", height = 8, width = 14)

ggplot(plotting.df2, aes(y=NES, x=reorder(Pathway,-log10FDR.qval), fill=log10FDR.qval)) + geom_bar(stat="identity")+scale_fill_gradient(low="red", high="blue", name = "-log10(FDR q-value)") +
  ylab("NES") + theme_minimal() + theme(legend.position = "right",
                                     axis.text.x = element_text(angle = 90, hjust = 0.95, face = "bold")) + guides(color=guide_legend("-log10(FDR q-value)"))
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/MBC-like-MBC_vs_PC-like-MBC_GSEA_Barplot_Rotated.png", height = 6, width = 12)

ggplot(plotting.df3, aes(y=NES, x=reorder(Pathway,-log10FDR.qval), fill=log10FDR.qval)) + geom_bar(stat="identity")+scale_fill_gradient(low="red", high="blue", name = "-log10(FDR q-value)") +
  ylab("NES") + theme_minimal(base_size = 15) + theme(legend.position = "right",
                                     axis.text.x = element_text(angle = 90, hjust = 0.95, face = "bold")) + guides(color=guide_legend("-log10(FDR q-value)"))
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/Clonal-MBC_vs_Reference-MBC_GSEA_Barplot_Rotated.png", height = 6, width = 18)
```

```{r}
# regular FDR
ggplot(plotting.df, aes(x=NES, y=reorder(Pathway,-FDR.q.val), size = Size)) + geom_point(aes(size=Count, color = FDR.q.val)) + scale_color_gradient(low = "blue", high = "red", name = "FDR q-value") +
  ylab("") + ggtitle("Clonal PC Enriched Pathways") + theme_bw() + theme(legend.position = "right") 
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/ClonalPC_vs_RefPC_GSEA_Dotplot_upClonalPC_FDRqval.png", height = 8, width = 8)

ggplot(plotting.df2, aes(x=NES, y=reorder(Pathway,-FDR.q.val),size = Size)) + geom_point(aes(size=Count, color = FDR.q.val)) + scale_color_gradient(low = "blue", high = "red", name = "FDR q-value") +
  ylab("") + ggtitle("Refrence PC Enriched Pathways") + theme_bw() + theme(legend.position = "right") 
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/ClonalPC_vs_RefPC_GSEA_Dotplot_upRefPC_FDRqval.png", height = 8, width = 8)
```

