---
title: "Post_CellTypist_MiloPrep"
output: html_document
date: "2023-01-01"
---

# Libraries
```{r}
library(Seurat)
#library(SeuratDisk)
library(anndata)
library(zellkonverter)
library(ggplot2)
library(scran)
library(scater)
options(future.globals.maxSize=1000000000000000000) # Set max global size so we don't run out of memory
```
# Load in AnnData H5 object and convert to Seurat object
```{r}
h5 <- readH5AD("/Users/gagled01/morganLab/Waldenstroms/singlecell/objects/scRNA_SCTransformed_Integrated_ReferenceAdd_CellTypistAnnotated.h5ad", verbose = TRUE)
celltypist.object <- as.Seurat(h5, counts = "X", data = NULL)

scrna.object <- readRDS("/Users/gagled01/morganLab/Waldenstroms/singlecell/objects/scRNA_SCTransformed_Integrated_ReferenceAdd.rds")
```
# Fix possible cell mismatches and assign new celltype variables
```{r}
mismatch <- setdiff(rownames(celltypist.object@meta.data), rownames(scrna.object@meta.data))
print(paste0("number of mismatched cells = ", length(mismatch)))
celltypist.object <- celltypist.object[,!colnames(celltypist.object) %in% mismatch]

scrna.object@meta.data$majority_voting <- celltypist.object@meta.data$majority_voting
scrna.object@meta.data$conf_score <- celltypist.object@meta.data$conf_score
scrna.object@meta.data$predicted_labels <- celltypist.object@meta.data$predicted_labels
```
What do we have?
```{r}
table(scrna.object@meta.data$majority_voting)

DimPlot(scrna.object, group.by = "majority_voting", raster = F)
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_ReferenceAdd_Regress_SCTransformInt_CTAnnotationUMAP_Unfiltered_Rerun_NoRegress.png", height = 6, width = 12)
```
Filtering B cells
```{r}
rm(celltypist.object, h5) # remove these objects to save memory so this shit doesn't crash
scrna.object_filt <- subset(scrna.object, subset = majority_voting %in% c("Age-associated B cells", "Large pre-B cells", "Germinal center B cells", "Pro-B cells", "Memory B cells", "Naive B cells", "Proliferative germinal center B cells", "Small pre-B cells", "Plasma cells")) 
scrna.object_filt@meta.data$majority_voting <- droplevels(scrna.object_filt@meta.data$majority_voting)

DimPlot(scrna.object_filt, group.by = "majority_voting", raster = F)
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_ReferenceAdd_Regress_SCTransformInt_CTAnnotationUMAP_Filtered_Rerun_NoRegress.png", height = 6, width = 8)
```
Save it out
```{r}
saveRDS(scrna.object_filt, "/Users/gagled01/morganLab/Waldenstroms/singlecell/objects/scRNA_SCTransformIntegrated_CTAnnotated_ReferenceAdd_Filtered_NoRegress.rds")
```

# Rerun standard workflow to see clustering with only B cells
```{r}
rm(scrna.object) # remove original object so it doesn't crash

DefaultAssay(scrna.object_filt) <- "integrated" # set default assay to integrated
scrna.object_filt <- ScaleData(scrna.object_filt)
scrna.object_filt <- RunPCA(scrna.object_filt, npcs = 20)
scrna.object_filt <- FindNeighbors(scrna.object_filt, dims = 1:20)
scrna.object_filt <- FindClusters(scrna.object_filt, resolution = 0.5)
scrna.object_filt <- RunUMAP(scrna.object_filt, dims = 1:20)

DimPlot(scrna.object_filt, raster = F, group.by = "majority_voting")
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_ReferenceAdd_SCTransformInt_CTAnnotationUMAP_Filtered_Reclustered_NoRegress_Celltype.png", height = 6, width = 8)
DimPlot(scrna.object_filt, raster = F, group.by = "condition")
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_ReferenceAdd_SCTransformInt_CTAnnotationUMAP_Filtered_Reclustered_NoRegress_Condition.png", height = 6, width = 8)
DimPlot(scrna.object_filt, raster = F, group.by = "source")
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_ReferenceAdd_SCTransformInt_CTAnnotationUMAP_Filtered_Reclustered_NoRegress_Source.png", height = 6, width = 8)
DimPlot(scrna.object_filt, raster = F, group.by = "tissue")
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_ReferenceAdd_SCTransformInt_CTAnnotationUMAP_Filtered_Reclustered_NoRegress_Tissue.png", height = 6, width = 8)
table(scrna.object_filt@meta.data$majority_voting)
```

# Code storage
```{r}
ElbowPlot(
  object = scrna.object_filt, 
  ndims = 20
) +
  geom_abline(
    aes(intercept = 1.75, slope = 0, color = "red"),
    show.legend = FALSE
  )
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_SCTransform_Integrated_20PCs_ElbowPlot.png", height = 6, width = 8)

#scrna.object <- RunPCA(scrna.object, npcs = 20)
```

