---
title: "h5_to_Seurat"
output: html_document
date: "2023-01-01"
---
Code for converting AnnData h5 object output by CellTypist back into a Seurat object.

# Libraries
```{r}
library(Seurat)
#library(SeuratDisk)
library(anndata)
library(zellkonverter)
library(ggplot2)
library(scran)
library(scater)
options(future.globals.maxSize=1000000000000000000) # Set max global size so we don't run out of memory
```
# Load in AnnData H5 object and convert to Seurat object
```{r}
h5 <- readH5AD("/Users/gagled01/morganLab/Waldenstroms/singlecell/objects/scRNA_SCTransformed_Integrated_CellTypistAnnotated.h5ad", verbose = TRUE)
celltypist.object <- as.Seurat(h5, counts = "X", data = NULL)

scrna.object <- readRDS("/Users/gagled01/morganLab/Waldenstroms/singlecell/objects/scRNA_SCTransformed_Integrated.rds")
```
# Fix possible cell mismatches and assign new celltype variables
```{r}
mismatch <- setdiff(rownames(celltypist.object@meta.data), rownames(scrna.object@meta.data))
print(paste0("number of mismatched cells = ", length(mismatch)))
celltypist.object <- celltypist.object[,!colnames(celltypist.object) %in% mismatch]

scrna.object@meta.data$majority_voting <- celltypist.object@meta.data$majority_voting
scrna.object@meta.data$conf_score <- celltypist.object@meta.data$conf_score
scrna.object@meta.data$predicted_labels <- celltypist.object@meta.data$predicted_labels
```
# Take a look
```{r}
table(scrna.object@meta.data$majority_voting)
DimPlot(scrna.object, group.by = "majority_voting", raster = F)
```


