---
title: "scRNA_DownstreamAnalysis"
output: html_document
date: "2023-08-03"
---

Load libraries
```{r}
library(Seurat)
library(ggplot2)
library(dplyr)
options(future.globals.maxSize=10000000000000000)
```
Load data
```{r}
seurobj <- readRDS("/Users/gagled01/morganLab/Waldenstroms/singlecell/objects/scRNA_SCTransformIntegrated_CTAnnotatedCleaned.rds")
```
All basic metrics
```{r}
p1 <- DimPlot(seurobj, reduction = "umap", group.by = "source")
p2 <- DimPlot(seurobj, reduction = "umap", group.by = "patient")
p3 <- DimPlot(seurobj, reduction = "umap", group.by = "batch")
p1 | p2 | p3
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_SCTIntegrated_CTAnnotatedClean_BasicUMAPs_Horizontal.png", height = 4, width = 12)

p1 / p2 / p3 
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_SCTIntegrated_CTAnnotatedClean_BasicUMAPs_Vertical.png", height = 12, width = 5)
```

Cleaned annotated UMAP
```{r}
p1 <- DimPlot(seurobj, group.by = "majority_voting")
p1
```

```{r}
DefaultAssay(seurobj) <- "RNA"
Idents(seurobj) <- "majority_voting"

all.markers <- FindAllMarkers(seurobj)

memory.b.markers <- all.markers[all.markers$cluster == "Memory B cells",]

temp <- memory.b.markers %>% arrange(p_val_adj)

```
```{r}
DefaultAssay(seurobj) <- "SCT"
FeaturePlot(seurobj, features = c("CD19", "MS4A1", "CD38", "CD27",
                                     "CD24", "SDC1", "BCL6", "PAX5",
                                     "CD44", "MME", "CXCR4", "CXCR5"))
ggsave("/Users/gagled01/morganLab/Waldenstroms/singlecell/figures/scRNA_SCTIntegrated_CTAnnotatedClean_FeaturePlots.png", height = 12, width = 16)
```